In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('excel/Ehouse.csv')
df.head()

,Column1,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,Column11,Column12,Column13,Column14,Column15,Column16,Column17,Column18,Column19,Column20
0,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
2,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
3,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [4]:
df.columns = df.iloc[0]
df = df[1:].reset_index(drop = True)

In [5]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [6]:
df.shape

(1040, 19)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1040 entries, 0 to 1039
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1040 non-null   object
 1   society          452 non-null    object
 2   price            964 non-null    object
 3   rate             1011 non-null   object
 4   area             1040 non-null   object
 5   areaWithType     981 non-null    object
 6   bedRoom          981 non-null    object
 7   bathroom         981 non-null    object
 8   balcony          981 non-null    object
 9   additionalRoom   589 non-null    object
 10  address          1016 non-null   object
 11  noOfFloor        961 non-null    object
 12  facing           672 non-null    object
 13  agePossession    981 non-null    object
 14  nearbyLocations  900 non-null    object
 15  description      1021 non-null   object
 16  furnishDetails   740 non-null    object
 17  features         673 non-null    object
 18  rating           893 non-null    object
dtypes: object(19)
memory usage: 154.5+ KB

### Check for duplicates

In [9]:
df.duplicated().sum()

np.int64(20)

In [11]:
df[df.duplicated()]

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
94,5 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,"₹ 19,708/sq.ft.",(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
95,4 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,"₹ 16,039/sq.ft.",(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
97,3 Bedroom House for sale in Sector 109 Gurgaon,International City by Sobha Phase 1,NaN,"₹ 11,100/sq.ft.",(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
100,4 Bedroom House for sale in Sector 112 Gurgaon,Experion Windchants3.8 ★,NaN,"₹ 12,027/sq.ft.",(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
109,3 Bedroom House for sale in Sector 48 Gurgaon,Vipul Tatvam Villa,NaN,"₹ 19,000/sq.ft.",(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
115,5 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,"₹ 16,058/sq.ft.",(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
116,4 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,"₹ 15,700/sq.ft.",(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
769,4 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.4 Crore,"₹ 20,690/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Store Room,Study Room,Servant Room","290 Sqyd Duplex Villa, Sector 70A Gurgaon, Gur...",3 Floors,North,1 to 5 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...","Bptp duplex villa 290 sqyd plot size, private ...","['5 Wardrobe', '1 Water Purifier', '6 Geyser',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
770,4 Bedroom House for sale in C Block Sushant Lo...,NaN,5.75 Crore,"₹ 29,716/sq.ft.",(180 sq.m.) Plot Area,Plot area 215(179.77 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Pooja Room,Store Room","C Block Sushant Lok Phase 1, Gurgaon, Haryana",2 Floors,North,10+ Year Old,"['Sector 42-43 metro station', 'Huda city cent...",North facing property\n100 meter from vaipar k...,NaN,"['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
771,3 Bedroom House for sale in Palam Vihar,NaN,2.55 Crore,"₹ 16,378/sq.ft.",(145 sq.m.) Plot Area,Plot area 173(144.65 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Palam Vihar, Gurgaon, Haryana",2 Floors,South,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",173 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Light', 'No AC', 'No Bed', 'No Ch...",['Park'],"['Environment5 out of 5', 'Lifestyle5 out of 5..."
772,8 Bedroom House for sale in Palam Vihar,NaN,5.6 Crore,"₹ 17,284/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),8 Bedrooms,6 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","Palam Vihar, Gurgaon, Haryana",NaN,South-West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",360 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Dining Table', '1 Light', '1 Modu...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
773,5 Bedroom House for sale in Greenwood City,NaN,17 Crore,"₹ 37,777/sq.ft.",(418 sq.m.) Plot Area,Plot area 4500(418.06 sq.m.),5 Bedrooms,8 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","0000, Greenwood City, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Huda city centre metro station', 'Axis bank ...",Ultra luxury kothi for sale in greenwood city ...,"['1 Water Purifier', '11 Fan', '1 Fridge', '1 ...","['Centrally Air Conditioned', 'Water purifier'...","['Environment4.5 out of 5', 'Lifestyle4 out of..."
774,4 Bedroom House for sale in Sector 112 Gurgaon,Experion Windchants3.8 ★,7.99 Crore,"₹ 12,519/sq.ft.",(593 sq.m.) Built-up Area,Built Up area: 6382 (592.91 sq.m.),4 Bedrooms,6 Bathrooms,3 Balconies,"Servant Room,Store Room,Pooja Room","Wp1- Wp-8, Sector 112 Gurgaon, Gurgaon, Haryana",2 Floors,South-East,0 to 1 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Available for sale 4bhk + servant luxury villa...,"['1 Exhaust Fan', '7 Geyser', '1 Stove', '10 A...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
775,6 Bedroom House for sale in Uppals Southend,Uppal Southend4.0 ★,3.75 Crore,"₹ 25,562/sq.ft.",(136 sq.m.) Plot Area,Plot area 163(136.29 sq.m.),6 Bedrooms,6 Bathrooms,3 Balconies,Others,"Uppals Southend, Gurgaon, Haryana",3 Floors,East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address...Uppal southend sector 49 w blook \n6...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
776,3 Bedroom House for sale in Sector 48 Gurgaon,Vipul Tatvam Villa,7.25 Crore,"₹ 27,971/sq.ft.",(241 sq.m.) Plot Area,Plot area 288(240.8 sq.m.),3 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Study Room,Store Room,Pooja Room","A111, Sector 48 Gurgaon, Gurgaon, Haryana",2 Floors,South,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Sector 48 gurgaon is one of gurgaon's most sou...,"['4 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
777,4 Bedroom House for sale in Sector 48 Gurgaon,Vipul Tatvam Villa,8.4 Crore,"₹ 21,000/sq.ft.",(372 sq.m.) Plot Area,Plot area 4000(371.61 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room","Sector 48 Gurgaon, Gurgaon, Haryana",2 Floors,North,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Wishing to settle down in an individual house ...,"['5 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
778,4 Bedroom House for sale in Sector 55 Gurgaon,NaN,3.55 Crore,"₹ 24,500/sq.ft.",(135 sq.m.) Plot Area,Plot area 161(134.62 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 55 Gurgaon, Gurgaon, Haryana",2 Floors,NaN,10+ Year Old,"['Sector metro station', 'Sector metro station...",For sale 161yd independent house sector 55 gur...,"['6 Wardrobe', '9 Fan', '6 Geyser', '17 Light'...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
779,4 Bedroom House for sale in Sector 91 Gurgaon,DLF New Town Heights3.7 ★,2.5 Crore,"₹ 7,058/sq.ft.",(316 sq.m.) Plot Area,Plot area 3400(315.87 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","Sector 91 Gurgaon, Gurgaon, Haryana",3 Floors,East,5 to 10 Year Old,"['MG Road Metro Station', 'RHM Public School',...","Dlf new town heights, 4bhk independent villa a...","['2 Bed', '7 Wardrobe', '9 Fan', '1 Exhaust Fa...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
780,4 Bedroom House for sale in Sector 86 Gurgaon,DLF New Town Heights 24.0 ★,2.5 Crore,"₹ 7,058/sq.ft.",(316 sq.m.) Plot Area,Plot area 3400(315.87 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Study Room,Servant Room,Pooja Room,Store Room","Sector 86 Gurgaon, Gurgaon, Haryana",3 Floors,East,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...","Dlf new town heights, 4bhk independent villa a...","['2 Bed', '7 Wardrobe', '12 Fan', '1 Exhaust F...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
820,12 Bedroom House for sale in DLF Phase 1,Luxury DLF City Floors,8.25 Crore,"₹ 45,833/sq.ft.",(167 sq.m.) Plot Area,Plot area 200(167.23 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Servant Room,"A Block Dlf-1, DLF Phase 1, Gurgaon, Haryana",4 Floors,North,0 to 1 Year Old,"['Sikandarpur metro station', 'Sikanderpur met...",For sale brand new building having stilt and 4...,"['20 Fan', '1 Exhaust Fan', '12 Geyser', '40 L...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [12]:
df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist())

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
741,12 Bedroom House for sale in DLF Phase 1,Luxury DLF City Floors,8.25 Crore,"₹ 45,833/sq.ft.",(167 sq.m.) Plot Area,Plot area 200(167.23 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Servant Room,"A Block Dlf-1, DLF Phase 1, Gurgaon, Haryana",4 Floors,North,0 to 1 Year Old,"['Sikandarpur metro station', 'Sikanderpur met...",For sale brand new building having stilt and 4...,"['20 Fan', '1 Exhaust Fan', '12 Geyser', '40 L...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
820,12 Bedroom House for sale in DLF Phase 1,Luxury DLF City Floors,8.25 Crore,"₹ 45,833/sq.ft.",(167 sq.m.) Plot Area,Plot area 200(167.23 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Servant Room,"A Block Dlf-1, DLF Phase 1, Gurgaon, Haryana",4 Floors,North,0 to 1 Year Old,"['Sikandarpur metro station', 'Sikanderpur met...",For sale brand new building having stilt and 4...,"['20 Fan', '1 Exhaust Fan', '12 Geyser', '40 L...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
50,3 Bedroom House for sale in Palam Vihar,NaN,2.55 Crore,"₹ 16,378/sq.ft.",(145 sq.m.) Plot Area,Plot area 173(144.65 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Palam Vihar, Gurgaon, Haryana",2 Floors,South,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",173 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Light', 'No AC', 'No Bed', 'No Ch...",['Park'],"['Environment5 out of 5', 'Lifestyle5 out of 5..."
771,3 Bedroom House for sale in Palam Vihar,NaN,2.55 Crore,"₹ 16,378/sq.ft.",(145 sq.m.) Plot Area,Plot area 173(144.65 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Palam Vihar, Gurgaon, Haryana",2 Floors,South,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",173 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Light', 'No AC', 'No Bed', 'No Ch...",['Park'],"['Environment5 out of 5', 'Lifestyle5 out of 5..."
91,3 Bedroom House for sale in Sector 109 Gurgaon,International City by Sobha Phase 1,NaN,"₹ 11,100/sq.ft.",(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
97,3 Bedroom House for sale in Sector 109 Gurgaon,International City by Sobha Phase 1,NaN,"₹ 11,100/sq.ft.",(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
55,3 Bedroom House for sale in Sector 48 Gurgaon,Vipul Tatvam Villa,7.25 Crore,"₹ 27,971/sq.ft.",(241 sq.m.) Plot Area,Plot area 288(240.8 sq.m.),3 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Study Room,Store Room,Pooja Room","A111, Sector 48 Gurgaon, Gurgaon, Haryana",2 Floors,South,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Sector 48 gurgaon is one of gurgaon's most sou...,"['4 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
776,3 Bedroom House for sale in Sector 48 Gurgaon,Vipul Tatvam Villa,7.25 Crore,"₹ 27,971/sq.ft.",(241 sq.m.) Plot Area,Plot area 288(240.8 sq.m.),3 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Study Room,Store Room,Pooja Room","A111, Sector 48 Gurgaon, Gurgaon, Haryana",2 Floors,South,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Sector 48 gurgaon is one of gurgaon's most sou...,"['4 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
106,3 Bedroom House for sale in Sector 48 Gurgaon,Vipul Tatvam Villa,NaN,"₹ 19,000/sq.ft.",(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
109,3 Bedroom House for sale in Sector 48 Gurgaon,Vipul Tatvam Villa,NaN,"₹ 19,000/sq.ft.",(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
49,4 Bedroom House for sale in C Block Sushant Lo...,NaN,5.75 Crore,"₹ 29,716/sq.ft.",(180 sq.m.) Plot Area,Plot area 215(179.77 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Pooja Room,Store Room","C Block Sushant Lok Phase 1, Gurgaon, Haryana",2 Floors,North,10+ Year Old,"['Sector 42-43 metro station', 'Huda city cent...",North facing property\n100 meter from vaipar k...,NaN,"['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
770,4 Bedroom House for sale in C Block Sushant Lo...,NaN,5.75 Crore,"₹ 29,716/sq.ft.",(180 sq.m.) Plot Area,Plot area 215(179.77 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Pooja Room,Store Room","C Block Sushant Lok Phase 1, Gurgaon, Haryana",2 Floors,North,10+ Year Old,"['Sector 42-43 metro station', 'Huda city cent...",North facing property\n100 meter from vaipar k...,NaN,"['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
53,4 Bedroom House for sale in Sector 112 Gurgaon,Experion Windchants3.8 ★,7.99 Crore,"₹ 12,519/sq.ft.",(593 sq.m.) Built-up Area,Built Up area: 6382 (592.91 sq.m.),4 Bedrooms,6 Bathrooms,3 Balconies,"Servant Room,Store Room,Pooja Room","Wp1- Wp-8, Sector 112 Gurgaon, Gurgaon, Haryana",2 Floors,South-East,0 to 1 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Available for sale 4bhk + servant luxury villa...,"['1 Exhaust Fan', '7 Geyser', '1 Stove', '10 A...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
774,4 Bedroom House for sale in Sector 112 Gurgaon,Experion Windchants3.8 ★,7.99 Crore,"₹ 12,519/sq.ft.",(593 sq.m.) Built-up Area,Built Up area: 6382 (592.91 sq.m.),4 Bedrooms,6 Bathrooms,3 Balconies,"Servant Room,Store Room,Pooja Room","Wp1- Wp-8, Sector 112 Gurgaon, Gurgaon, Haryana",2 Floors,South-East,0 to 1 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Available for sale 4bhk + servant luxury villa...,"['1 Exhaust Fan', '7 Geyser', '1 Stove', '10 A...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
84,4 Bedroom House for sale in Sector 112 Gurgaon,Experion Windchants3.8 ★,NaN,"₹ 12,027/sq.ft.",(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
100,4 Bedroom House for sale in Sector 112 Gurgaon,Experion Windchants3.8 ★,NaN,"₹ 12,027/sq.ft.",(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
56,4 Bedroom House for sale in Sector 48 Gurgaon,Vipul Tatvam Villa,8.4 Crore,"₹ 21,000/sq.ft.",(372 sq.m.) Plot Area,Plot area 4000(371.61 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room","Sector 48 Gurgaon, Gurgaon, Haryana",2 Floors,North,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Wishing to settle down in an individual house ...,"['5 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
777,4 Bedroom House for sale in Sector 48 Gurgaon,Vipul Tatvam Villa,8.4 Crore,"₹ 21,000/sq.ft.",(372 sq.m.) Plot Area,Plot area 4000(371.61 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room","Sector 48 Gurgaon, Gurgaon, Haryana",2 Floors,North,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Wishing to settle down in an individual house ...,"['5 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
57,4 Bedroom House for sale in Sector 55 Gurgaon,NaN,3.55 Crore,"₹ 24,500/sq.ft.",(135 sq.m.) Plot Area,Plot area 161(134.62 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 55 Gurgaon, Gurgaon, Haryana",2 Floors,NaN,10+ Year Old,"['Sector metro station', 'Sector metro station...",For sale 161yd independent house sector 55 gur...,"['6 Wardrobe', '9 Fan', '6 Geyser', '17 Light'...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
778,4 Bedroom House for sale in Sector 55 Gurgaon,NaN,3.55 Crore,"₹ 24,500/sq.ft.",(135 sq.m.) Plot Area,Plot area 161(134.62 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 55 Gurgaon, Gurgaon, Haryana",2 Floors,NaN,10+ Year Old,"['Sector metro station', 'Sector metro station...",For sale 161yd independent house sector 55 gur...,"['6 Wardrobe', '9 Fan', '6 Geyser', '17 Light'...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
85,4 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,"₹ 15,700/sq.ft.",(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
116,4 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,"₹ 15,700/sq.ft.",(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
87,4 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,"₹ 16,039/sq.ft.",(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
95,4 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,"₹ 16,039/sq.ft.",(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
48,4 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.4 Crore,"₹ 20,690/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Store Room,Study Room,Servant Room","290 Sqyd Duplex Villa, Sector 70A Gurgaon, Gur...",3 Floors,North,1 to 5 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...","Bptp duplex villa 290 sqyd plot size, private ...","['5 Wardrobe', '1 Water Purifier', '6 Geyser',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
769,4 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.4 Crore,"₹ 20,690/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Store Room,Study Room,Servant Room","290 Sqyd Duplex Villa, Sector 70A Gurgaon, Gur...",3 Floors,North,1 to 5 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...","Bptp duplex villa 290 sqyd plot size, private ...","['5 Wardrobe', '1 Water Purifier', '6 Geyser',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
59,4 Bedroom House for sale in Sector 86 Gurgaon,DLF New Town Heights 24.0 ★,2.5 Crore,"₹ 7,058/sq.ft.",(316 sq.m.) Plot Area,Plot area 3400(315.87 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Study Room,Servant Room,Pooja Room,Store Room","Sector 86 Gurgaon, Gurgaon, Haryana",3 Floors,East,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...","Dlf new town heights, 4bhk independent villa a...","['2 Bed', '7 Wardrobe', '12 Fan', '1 Exhaust F...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
780,4 Bedroom House for sale in Sector 86 Gurgaon,DLF New Town Heights 24.0 ★,2.5 Crore,"₹ 7,058/sq.ft.",(316 sq.m.) Plot Area,Plot area 3400(315.87 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Study Room,Servant Room,Pooja Room,Store Room","Sector 86 Gurgaon, Gurgaon, Haryana",3 Floors,East,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...","Dlf new town heights, 4bhk independent villa a...","['2 Bed', '7 Wardrobe', '12 Fan', '1 Exhaust F...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
58,4 Bedroom House for sale in Sector 91 Gurgaon,DLF New Town Heights3.7 ★,2.5 Crore,"₹ 7,058/sq.ft.",(316 sq.m.) Plot Area,Plot area 3400(315.87 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","Sector 91 Gurgaon, Gurgaon, Haryana",3 Floors,East,5 to 10 Year Old,"['MG Road Metro Station', 'RHM Public School',...","Dlf new town heights, 4bhk independent villa a...","['2 Bed', '7 Wardrobe', '9 Fan', '1 Exhaust Fa...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
779,4 Bedroom House for sale in Sector 91 Gurgaon,DLF New Town Heights3.7 ★,2.5 Crore,"₹ 7,058/sq.ft.",(316 sq.m.) Plot Area,Plot area 3400(315.87 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","Sector 91 Gurgaon, Gurgaon, Haryana",3 Floors,East,5 to 10 Year Old,"['MG Road Metro Station', 'RHM Public School',...","Dlf new town heights, 4bhk independent villa a...","['2 Bed', '7 Wardrobe', '9 Fan', '1 Exhaust Fa...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
52,5 Bedroom House for sale in Greenwood City,NaN,17 Crore,"₹ 37,777/sq.ft.",(418 sq.m.) Plot Area,Plot area 4500(418.06 sq.m.),5 Bedrooms,8 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","0000, Greenwood City, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Huda city centre metro station', 'Axis bank ...",Ultra luxury kothi for sale in greenwood city ...,"['1 Water Purifier', '11 Fan', '1 Fridge', '1 ...","['Centrally Air Conditioned', 'Water purifier'...","['Environment4.5 out of 5', 'Lifestyle4 out of..."
773,5 Bedroom House for sale in Greenwood City,NaN,17 Crore,"₹ 37,777/sq.ft.",(418 sq.m.) Plot Area,Plot area 4500(418.06 sq.m.),5 Bedrooms,8 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","0000, Greenwood City, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Huda city centre metro station', 'Axis bank ...",Ultra luxury kothi for sale in greenwood city ...,"['1 Water Purifier', '11 Fan', '1 Fridge', '1 ...","['Centrally Air Conditioned', 'Water purifier'...","['Environment4.5 out of 5', 'Lifestyle4 out of..."
79,5 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,"₹ 16,058/sq.ft.",(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
115,5 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,"₹ 16,058/sq.ft.",(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
86,5 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,"₹ 19,708/sq.ft.",(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
94,5 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,"₹ 19,708/sq.ft.",(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
54,6 Bedroom House for sale in Uppals Southend,Uppal Southend4.0 ★,3.75 Crore,"₹ 25,562/sq.ft.",(136 sq.m.) Plot Area,Plot area 163(136.29 sq.m.),6 Bedrooms,6 Bathrooms,3 Balconies,Others,"Uppals Southend, Gurgaon, Haryana",3 Floors,East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address...Uppal southend sector 49 w blook \n6...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
775,6 Bedroom House for sale in Uppals Southend,Uppal Southend4.0 ★,3.75 Crore,"₹ 25,562/sq.ft.",(136 sq.m.) Plot Area,Plot area 163(136.29 sq.m.),6 Bedrooms,6 Bathrooms,3 Balconies,Others,"Uppals Southend, Gurgaon, Haryana",3 Floors,East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address...Uppal southend sector 49 w blook \n6...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
51,8 Bedroom House for sale in Palam Vihar,NaN,5.6 Crore,"₹ 17,284/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),8 Bedrooms,6 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","Palam Vihar, Gurgaon, Haryana",NaN,South-West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",360 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Dining Table', '1 Light', '1 Modu...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
772,8 Bedroom House for sale in Palam Vihar,NaN,5.6 Crore,"₹ 17,284/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),8 Bedrooms,6 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","Palam Vihar, Gurgaon, Haryana",NaN,South-West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",360 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Dining Table', '1 Light', '1 Modu...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [13]:
df = df.drop_duplicates()

In [14]:
df.shape

(1020, 19)

### Next Steps

In [15]:
df.isnull().sum()

0
property_name        0
society            583
price               69
rate                29
area                 0
areaWithType        52
bedRoom             52
bathroom            52
balcony             52
additionalRoom     442
address             24
noOfFloor           71
facing             360
agePossession       52
nearbyLocations    140
description         19
furnishDetails     291
features           359
rating             147
dtype: int64

In [22]:
df = df.copy()

In [23]:
# Renaming
df.rename(columns = {'rate' : 'price_sq.feet'}, inplace=True)
df.head()

,property_name,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,nan,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,nan,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,nan,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,nan,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### Society

In [17]:
df['society'].value_counts()

society
International City by SOBHA Phase 2                  24
Vipul Tatvam Villa                                   24
Emaar MGF Marbella                                   22
International City by Sobha Phase 1                  19
Unitech Uniworld Resorts                             14
DLF City Plots Phase 2                               11
Unitech Espace                                       11
DLF City Plots                                       11
Eldeco Mansionz                                       9
Uppal Southend4.0 ★                                   8
Bptp Visionnaire                                      8
Not Applicable                                        7
Sushant Lok 1 Builder Floors                          6
Ansals Palam Vihar                                    6
DLF City Phase 1                                      5
Ansals Florence Villa                                 4
Unitech Aspen Greens                                  4
DLF Alameda                                           4
Vatika India Next4.1 ★                                4
Experion Windchants3.8 ★                              4
DLF New Town Heights 24.0 ★                           4
Ansal Sushant Lok Plots4.1 ★                          4
nul                                                   4
Rattan Garden                                         3
Housing Board Colony                                  3
Palam Vihar Extension West Zone RWA                   3
Eros Rosewood City4.0 ★                               3
Malibu Towne                                          3
SS Aaron Ville                                        3
Vatika Signature Villas                               3
Sector 14 RWA                                         3
Tata Primanti4.1 ★                                    3
Anant Raj Estates                                     3
Eros Rosewood Villas                                  3
DLF City Plots Phase 3                                3
BPTP Astaire Gardens3.7 ★                             3
Puri Diplomatic Greens4.0 ★                           3
Unitech Nirvana Birch Court                           3
Suncity Township4.1 ★                                 2
Hans Enclave                                          2
Sector 38 RWA                                         2
Emaar The Palm Springs                                2
IFFCO Nagar and 17B RWA                               2
Bhim Garh Kheri                                       2
Sobha City                                            2
RWA Sector 46                                         2
BPTP Pedestal                                         2
Ardee City3.8 ★                                       2
Unitech Palms South City 1                            2
Project Mianwali Colony                               2
Nirvana Cedar Crest                                   2
Saksham Welfare Association                           2
Unitech Escape3.8 ★                                   2
SS Hibiscus                                           2
Satya The Hermitage3.5 ★                              2
Project Housing Board Colony                          2
Silverglades Tarudhan Valley Golf Resort              2
DLF South City 1                                      2
Ansal API Esencia3.7 ★                                2
Emaar Emerald Hills4.1 ★                              2
Central Park Flower Valley                            2
Ansal Sushant Residency                               2
shivpuri                                              2
Suncity Essel Towers4.2 ★                             2
Spaze Privy3.9 ★                                      2
Unitech Deerwood Chase                                2
Luxury DLF City Floors                                2
Ashok vihar phase III Extension                       1
huda sector-56 gurgaon                                1
Ireo Victory Valley4.1 ★                              1
All Punjabi Welfare Association                       1
4S Aradhya Homes                                      1
Ansal API Spanish Court                               1
Adani Brahma Samsara4.2 ★                             1
Central Park Flower Valley Cerise Floors              1
DLF City Plot Phase 3                                 1
Birla Navya                                           1
Kothi                                                 1
Sector-17C                                            1
Ansal                                                 1
DLF City Plots Phase 4                                1
nirvana country                                       1
Landmark House                                        1
Signature Global City 63A                             1
rattan vihar rajendra park                            1
private house                                         1
cloudnine cottages                                    1
u block dlf phase 3 road no 21                        1
Sector 15 Part 2 RWA                                  1
Nitin Vihar                                           1
Ansal Florence Super                                  1
house number B-34                                     1
Smart World Orchard                                   1
Bestech Park View Ananda4.2 ★                         1
Huda Floor                                            1
Huda                                                  1
Sector 57 Huda                                        1
Godrej Meridien                                       1
Ansal Sushant Lok 2                                   1
The Laburnum                                          1
Vatika Independent Floors3.8 ★                        1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
Grover Homes Sec 4                                    1
DLF Pink Town House4.0 ★                              1
FLOOR WISE DESIGNER KOTHI                             1
Satya The Legend3.8 ★                                 1
Ireo Victory Valley4.0 ★                              1
Unitech South City 23.8 ★                             1
Independent House Sector 45                           1
sector 37                                             1
DLF New Town Heights3.7 ★                             1
Unitech Greenwood City3.6 ★                           1
Vatika The Seven Lamps3.8 ★                           1
Nirvana Country                                       1
Ansal Sushant Lok                                     1
Central Park                                          1
Signature Global City 81                              1
Signature Global City                                 1
DLF Floors Phase 3                                    1
Sheetla Enclave                                       1
sneh vihar                                            1
SS Omnia                                              1
Suncity Avenue 76                                     1
Signature Global Park4.0 ★                            1
Laxmi Garden Sector-11                                1
HUDA Housing Board Colony4.1 ★                        1
Tulip Yellow                                          1
shree krishna homes                                   1
Smart World Gems                                      1
Ganpati Heights Apartment                             1
Hero Homes                                            1
Jacobpura Gurugram                                    1
Anand Garden, Sector-105                              1
Ninex City                                            1
RK Excelo                                             1
DLF The Grove                                         1
Surendra Homes Dayanand Colony                        1
My Home                                               1
ATS Tourmaline3.9 ★                                   1
Vatika Sovereign Next                                 1
MANOHAR NAGAR                                         1
Laxman vihar phase 2                                  1
Anamika Enclave                                       1
bhim nagar, sector 6                                  1
Surat nagar phase 2                                   1
Huda Plots                                            1
DLF Garden City Floors                                1
DLF The Arbour                                        1
DLF Gardencity Enclave                                1
Rajendra Park Gurgaon                                 1
Om Nagar, Sector-11                                   1
Bhawani enclave                                       1
Ansal Celebrity Homes                                 1
Shri Shyam Residency                                  1
mian wali                                             1
Ansal Heights3.2 ★                                    1
HUDA Ashok Vihar Phase 13.9 ★                         1
Anshul                                                1
Sare Crescent Parc Royal Greens Phase 1               1
Ashok Vihar Phase 3 Gurgaon                           1
Vipul World3.9 ★                                      1
Greenopolis                                           1
Ansal Esencia Sovereign Floors                        1
Nirmal Enclave, Maruti Kunj Road                      1
jacob pura                                            1
mahavir pura                                          1
Raj Villas                                            1
Farrukhnagar                                          1
Shivaji Nagar Residential                             1
Bhim Nagar Society                                    1
Prem Kunj                                             1
Signature Global City 92                              1
DLF City Plot Phase 4                                 1
Sai Kripa Floors 5                                    1
Naman Residency                                       1
Krishna Palace                                        1
secter 16a daultabad faridabad house no 313           1
Huda Flats                                            1
Jacobpura                                             1
Indiabulls Centrum Park3.7 ★                          1
Madan puri                                            1
rajendra park sec 105                                 1
ROW HOUSE                                             1
HUDA Plot Sector 38                                   1
Name: count, dtype: int64

In [18]:
df['society'].value_counts().shape

(184,)

In [24]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [25]:
df['society'].value_counts().shape

(182,)

In [26]:
df['society'] = df['society'].str.replace('nan', 'independent')

In [27]:
df.head(3)

,property_name,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### Price

In [28]:
df['price'].value_counts()

price
3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
5 Crore             13
8 Crore             13
4.5 Crore           13
50 Lac              13
75 Lac              13
70 Lac              13
7 Crore             12
85 Lac              12
8.5 Crore           12
4 Crore             11
1.5 Crore           11
60 Lac              10
2.5 Crore           10
2.25 Crore          10
9 Crore             10
10 Crore            10
90 Lac              10
45 Lac              10
80 Lac               9
1.1 Crore            9
1.7 Crore            9
2 Crore              9
9.5 Crore            9
12 Crore             9
1.6 Crore            8
4.6 Crore            8
11 Crore             8
6.75 Crore           8
1 Crore              8
1.35 Crore           7
1.3 Crore            7
55 Lac               7
12.5 Crore           7
65 Lac               7
3.75 Crore           7
1.2 Crore            7
2.1 Crore            7
95 Lac               7
40 Lac               7
Price on Request     6
3.25 Crore           6
2.75 Crore           6
1.15 Crore           6
10.5 Crore           6
7.5 Crore            6
2.95 Crore           6
16 Crore             6
13.5 Crore           6
6.25 Crore           6
1.45 Crore           6
3.6 Crore            6
4.25 Crore           6
5.7 Crore            6
2.8 Crore            5
3 Crore              5
15 Crore             5
38 Lac               5
1.8 Crore            5
7.25 Crore           5
4.75 Crore           5
5.6 Crore            5
35 Lac               5
1.25 Crore           5
37 Lac               4
2.4 Crore            4
5.25 Crore           4
42 Lac               4
1.4 Crore            4
5.8 Crore            4
6.8 Crore            4
5.75 Crore           4
17 Crore             4
8.25 Crore           4
13 Crore             4
4.35 Crore           4
18 Crore             4
3.2 Crore            4
11.5 Crore           4
9.25 Crore           4
1.65 Crore           4
4.7 Crore            4
3.3 Crore            4
19 Crore             3
2.9 Crore            3
6.4 Crore            3
1.9 Crore            3
62 Lac               3
2.2 Crore            3
4.3 Crore            3
1.85 Crore           3
92 Lac               3
1.16 Crore           3
34 Lac               3
32 Lac               3
2.3 Crore            3
49 Lac               3
82 Lac               3
5.15 Crore           3
3.4 Crore            3
6.95 Crore           3
1.95 Crore           3
8.4 Crore            3
4.45 Crore           3
3.1 Crore            3
20 Crore             3
7.35 Crore           3
7.2 Crore            3
3.85 Crore           3
1.55 Crore           3
5.65 Crore           3
19.5 Crore           2
4.95 Crore           2
14 Crore             2
58.25 Lac            2
2.15 Crore           2
48 Lac               2
9.9 Crore            2
7.1 Crore            2
1.05 Crore           2
3.55 Crore           2
2.55 Crore           2
10.85 Crore          2
11.95 Crore          2
3.51 Crore           2
3.15 Crore           2
3.35 Crore           2
8.49 Crore           2
89 Lac               2
10.45 Crore          2
26 Crore             2
15.5 Crore           2
67 Lac               2
1.75 Crore           2
3.65 Crore           2
58 Lac               2
6.3 Crore            2
11.25 Crore          2
10.55 Crore          2
3.05 Crore           2
36 Lac               2
11.75 Crore          2
30 Lac               2
66 Lac               2
4.49 Crore           1
4.15 Crore           1
6.15 Crore           1
8.45 Crore           1
2.47 Crore           1
3.7 Crore            1
18.4 Crore           1
10.3 Crore           1
22 Crore             1
9.4 Crore            1
6.21 Crore           1
7.3 Crore            1
12.25 Crore          1
46.75 Lac            1
10.75 Crore          1
52.75 Lac            1
5.88 Crore           1
18.5 Crore           1
2.01 Crore           1
3.9 Crore            1
5.1 Crore            1
27.5 Crore           1
99 Lac               1
8.31 Crore           1
1.83 Crore           1
4.4 Crore            1
1.64 Crore           1
2.65 Crore           1
1.18 Crore           1
9.01 Crore           1
9.8 Crore            1
4.99 Crore           1
8.6 Crore            1
9.55 Crore           1
2.35 Crore           1
18.25 Crore          1
5.3 Crore            1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
15.1 Crore           1
9.85 Crore           1
1.27 Crore           1
1.04 Crore           1
11.29 Crore          1
4.31 Crore           1
11.58 Crore          1
8.48 Crore           1
8.2 Crore            1
5.51 Crore           1
3.49 Crore           1
2.99 Crore           1
9.19 Crore           1
8.81 Crore           1
9.35 Crore           1
4.05 Crore           1
8.75 Crore           1
23 Crore             1
2.45 Crore           1
7.85 Crore           1
25 Crore             1
2.68 Crore           1
2.7 Crore            1
8.9 Crore            1
59 Lac               1
6.81 Crore           1
8.95 Crore           1
51 Lac               1
53 Lac               1
63 Lac               1
1.72 Crore           1
8.8 Crore            1
78 Lac               1
1.52 Crore           1
7.99 Crore           1
5.4 Crore            1
52 Lac               1
12.39 Crore          1
4.65 Crore           1
6.1 Crore            1
68 Lac               1
1.07 Crore           1
7.49 Crore           1
5.2 Crore            1
13.2 Crore           1
2.58 Crore           1
3.99 Crore           1
7.5 Lac              1
4.02 Crore           1
11.3 Crore           1
3.69 Crore           1
15.5 Lac             1
7.05 Crore           1
61 Lac               1
6.6 Crore            1
5.35 Crore           1
5.85 Crore           1
5.9 Crore            1
4.12 Crore           1
1.87 Crore           1
6.2 Crore            1
8.7 Crore            1
22 Lac               1
7.69 Crore           1
3.12 Crore           1
55.11 Lac            1
42.75 Lac            1
47 Lac               1
71 Lac               1
18.02 Crore          1
65.8 Lac             1
1.34 Crore           1
46 Lac               1
2.6 Crore            1
3.87 Crore           1
1.39 Crore           1
3.93 Crore           1
27 Lac               1
8.1 Crore            1
14.75 Crore          1
9.54 Crore           1
17.3 Crore           1
18.9 Crore           1
24 Crore             1
7.46 Crore           1
59.95 Lac            1
7.6 Crore            1
96 Lac               1
13 Lac               1
29 Lac               1
5.46 Crore           1
52.5 Lac             1
1.44 Crore           1
3.71 Crore           1
18 Lac               1
3.08 Crore           1
10.56 Crore          1
24 Lac               1
2.43 Crore           1
44 Lac               1
83 Lac               1
98 Lac               1
47.5 Lac             1
3.09 Crore           1
74 Lac               1
69 Lac               1
2.98 Crore           1
Name: count, dtype: int64

In [29]:
df = df[df['price'] != 'Price on Request']

In [30]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [33]:
if df['price'].dtype == 'object':
    df['price'] = df['price'].str.split(' ').apply(treat_price)

In [34]:
import warnings
warnings.simplefilter(action='ignore', category=pd.errors.SettingWithCopyWarning)

In [35]:
df.sample(3)

,property_name,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
849,12 Bedroom House for sale in Sector 40 Gurgaon,independent house sector 45,9.0,"₹ 38,022/sq.ft.",(220 sq.m.) Plot Area,Plot area 2367(219.9 sq.m.)Built Up area: 9000...,12 Bedrooms,12 Bathrooms,3 Balconies,Servant Room,"Adjoining 30mtr Road Building On Sale, Sector ...",4 Floors,North-West,0 to 1 Year Old,"['Huda city centre metro station', 'Axis bank ...",12bhk independent floorwise building on sale a...,"['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '5 Ge...","['Security / Fire Alarm', 'Private Garden / Te...","['Environment4 out of 5', 'Safety4 out of 5', ..."
231,3 Bedroom House for sale in Sector 93 Gurgaon,dlf gardencity enclave,1.3,"₹ 11,284/sq.ft.",(107 sq.m.) Plot Area,Plot area 1152(107.02 sq.m.),3 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Sector 93 Gurgaon, Gurgaon, Haryana",3 Floors,NaN,1 to 5 Year Old,"['Huda Metro Station', 'Omaxe City Centre', 'D...",I am looking for buyer to purchase house/villa...,[],NaN,NaN
637,7 Bedroom House for sale in Surat Nagar 1,independent,0.6,"₹ 5,128/sq.ft.",(109 sq.m.) Plot Area,Plot area 130(108.7 sq.m.),7 Bedrooms,3 Bathrooms,1 Balcony,NaN,"House No. 5215, Gali No.12, Surat Nagar 1, Gur...",2 Floors,North,5 to 10 Year Old,"['Ravi Clinic and Health Care Centre', 'D.R. R...",Very good property.. 1.5 km away from dwarka e...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

### price_sq.feet

In [37]:
df['price_sq.feet'].value_counts()

price_sq.feet
₹ 22,222/sq.ft.     14
₹ 11,111/sq.ft.     11
₹ 33,333/sq.ft.     11
₹ 10,000/sq.ft.     10
₹ 30,556/sq.ft.      6
₹ 13,333/sq.ft.      6
₹ 37,037/sq.ft.      6
₹ 31,481/sq.ft.      6
₹ 26,667/sq.ft.      6
₹ 26,235/sq.ft.      6
₹ 5,000/sq.ft.       5
₹ 8,000/sq.ft.       5
₹ 9,444/sq.ft.       5
₹ 23,333/sq.ft.      5
₹ 8,889/sq.ft.       5
₹ 23,148/sq.ft.      5
₹ 15,625/sq.ft.      4
₹ 18,889/sq.ft.      4
₹ 34,722/sq.ft.      4
₹ 21,605/sq.ft.      4
₹ 11,100/sq.ft.      4
₹ 32,407/sq.ft.      4
₹ 27,778/sq.ft.      4
₹ 9,722/sq.ft.       4
₹ 35,000/sq.ft.      4
₹ 24,691/sq.ft.      4
₹ 14,815/sq.ft.      3
₹ 20,000/sq.ft.      3
₹ 7,500/sq.ft.       3
₹ 60,000/sq.ft.      3
₹ 33,951/sq.ft.      3
₹ 12,222/sq.ft.      3
₹ 50,000/sq.ft.      3
₹ 8,333/sq.ft.       3
₹ 11,250/sq.ft.      3
₹ 25,000/sq.ft.      3
₹ 44,444/sq.ft.      3
₹ 17,037/sq.ft.      3
₹ 36,111/sq.ft.      3
₹ 5,555/sq.ft.       3
₹ 13,889/sq.ft.      3
₹ 6,944/sq.ft.       3
₹ 32,222/sq.ft.      3
₹ 6,666/sq.ft.       3
₹ 10,556/sq.ft.      3
₹ 12,000/sq.ft.      3
₹ 8,444/sq.ft.       3
₹ 8,235/sq.ft.       3
₹ 15,555/sq.ft.      3
₹ 29,880/sq.ft.      3
₹ 25,926/sq.ft.      3
₹ 11,574/sq.ft.      2
₹ 14,444/sq.ft.      2
₹ 29,630/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 10,101/sq.ft.      2
₹ 26,389/sq.ft.      2
₹ 9,000/sq.ft.       2
₹ 24,845/sq.ft.      2
₹ 100,000/sq.ft.     2
₹ 12,500/sq.ft.      2
₹ 12,963/sq.ft.      2
₹ 59,259/sq.ft.      2
₹ 26,852/sq.ft.      2
₹ 21,759/sq.ft.      2
₹ 12,342/sq.ft.      2
₹ 45,833/sq.ft.      2
₹ 38,580/sq.ft.      2
₹ 35,556/sq.ft.      2
₹ 10,518/sq.ft.      2
₹ 55,000/sq.ft.      2
₹ 23,457/sq.ft.      2
₹ 24,306/sq.ft.      2
₹ 37,627/sq.ft.      2
₹ 39,841/sq.ft.      2
₹ 75,000/sq.ft.      2
₹ 3,857/sq.ft.       2
₹ 38,194/sq.ft.      2
₹ 15,257/sq.ft.      2
₹ 24,155/sq.ft.      2
₹ 11,852/sq.ft.      2
₹ 20,833/sq.ft.      2
₹ 3,500/sq.ft.       2
₹ 10,753/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 8,888/sq.ft.       2
₹ 7,407/sq.ft.       2
₹ 20,635/sq.ft.      2
₹ 42,222/sq.ft.      2
₹ 16,975/sq.ft.      2
₹ 9,634/sq.ft.       2
₹ 18,928/sq.ft.      2
₹ 32,963/sq.ft.      2
₹ 13,910/sq.ft.      2
₹ 7,718/sq.ft.       2
₹ 17,778/sq.ft.      2
₹ 16,058/sq.ft.      2
₹ 25,535/sq.ft.      2
₹ 1,859/sq.ft.       2
₹ 10,579/sq.ft.      2
₹ 13,000/sq.ft.      2
₹ 42,194/sq.ft.      2
₹ 38,095/sq.ft.      2
₹ 38,760/sq.ft.      2
₹ 15,278/sq.ft.      2
₹ 21,124/sq.ft.      2
₹ 201,388/sq.ft.     2
₹ 17,187/sq.ft.      2
₹ 7,058/sq.ft.       2
₹ 24,500/sq.ft.      2
₹ 4,444/sq.ft.       2
₹ 48,148/sq.ft.      2
₹ 25,562/sq.ft.      2
₹ 17,284/sq.ft.      2
₹ 35,185/sq.ft.      2
₹ 32,328/sq.ft.      2
₹ 18,626/sq.ft.      1
₹ 17,857/sq.ft.      1
₹ 261,194/sq.ft.     1
₹ 82,540/sq.ft.      1
₹ 22,812/sq.ft.      1
₹ 18,888/sq.ft.      1
₹ 6,289/sq.ft.       1
₹ 6,778/sq.ft.       1
₹ 13,501/sq.ft.      1
₹ 1,649/sq.ft.       1
₹ 29,697/sq.ft.      1
₹ 20,988/sq.ft.      1
₹ 24,366/sq.ft.      1
₹ 28,898/sq.ft.      1
₹ 20,444/sq.ft.      1
₹ 7,168/sq.ft.       1
₹ 400,000/sq.ft.     1
₹ 21,296/sq.ft.      1
₹ 23,000/sq.ft.      1
₹ 27,461/sq.ft.      1
₹ 24,171/sq.ft.      1
₹ 28,200/sq.ft.      1
₹ 26,298/sq.ft.      1
₹ 178,571/sq.ft.     1
₹ 9,615/sq.ft.       1
₹ 10,067/sq.ft.      1
₹ 31,686/sq.ft.      1
₹ 27,222/sq.ft.      1
₹ 6,800/sq.ft.       1
₹ 63,554/sq.ft.      1
₹ 10,601/sq.ft.      1
₹ 20,940/sq.ft.      1
₹ 32,253/sq.ft.      1
₹ 23,704/sq.ft.      1
₹ 9,210/sq.ft.       1
₹ 14,890/sq.ft.      1
₹ 23,693/sq.ft.      1
₹ 15,989/sq.ft.      1
₹ 19,268/sq.ft.      1
₹ 6,000/sq.ft.       1
₹ 19,360/sq.ft.      1
₹ 13,750/sq.ft.      1
₹ 23,437/sq.ft.      1
₹ 26,973/sq.ft.      1
₹ 57,206/sq.ft.      1
₹ 38,889/sq.ft.      1
₹ 7,333/sq.ft.       1
₹ 10,582/sq.ft.      1
₹ 7,539/sq.ft.       1
₹ 23,061/sq.ft.      1
₹ 13,178/sq.ft.      1
₹ 17,662/sq.ft.      1
₹ 6,938/sq.ft.       1
₹ 84,000/sq.ft.      1
₹ 9,390/sq.ft.       1
₹ 20,068/sq.ft.      1
₹ 39,530/sq.ft.      1
₹ 4,260/sq.ft.       1
₹ 16,569/sq.ft.      1
₹ 14,184/sq.ft.      1
₹ 21,242/sq.ft.      1
₹ 32,562/sq.ft.      1
₹ 8,101/sq.ft.       1
₹ 22,429/sq.ft.      1
₹ 26,428/sq.ft.      1
₹ 11,157/sq.ft.      1
₹ 7,000/sq.ft.       1
₹ 8,254/sq.ft.       1
₹ 7,007/sq.ft.       1
₹ 308,333/sq.ft.     1
₹ 13,030/sq.ft.      1
₹ 8,920/sq.ft.       1
₹ 49,500/sq.ft.      1
₹ 35,294/sq.ft.      1
₹ 5,128/sq.ft.       1
₹ 25,463/sq.ft.      1
₹ 7,555/sq.ft.       1
₹ 5,777/sq.ft.       1
₹ 2,716/sq.ft.       1
₹ 14,285/sq.ft.      1
₹ 34,307/sq.ft.      1
₹ 51,864/sq.ft.      1
₹ 10,610/sq.ft.      1
₹ 5,093/sq.ft.       1
₹ 44,265/sq.ft.      1
₹ 10,085/sq.ft.      1
₹ 144,444/sq.ft.     1
₹ 15,046/sq.ft.      1
₹ 5,160/sq.ft.       1
₹ 24,074/sq.ft.      1
₹ 11,583/sq.ft.      1
₹ 6,034/sq.ft.       1
₹ 40,611/sq.ft.      1
₹ 7,302/sq.ft.       1
₹ 10,591/sq.ft.      1
₹ 29,629/sq.ft.      1
₹ 10,740/sq.ft.      1
₹ 17,980/sq.ft.      1
₹ 8,155/sq.ft.       1
₹ 19,737/sq.ft.      1
₹ 8,127/sq.ft.       1
₹ 29,444/sq.ft.      1
₹ 20,741/sq.ft.      1
₹ 13,492/sq.ft.      1
₹ 18,658/sq.ft.      1
₹ 33,592/sq.ft.      1
₹ 24,455/sq.ft.      1
₹ 194,444/sq.ft.     1
₹ 18,444/sq.ft.      1
₹ 11,600/sq.ft.      1
₹ 7,777/sq.ft.       1
₹ 10,484/sq.ft.      1
₹ 6,813/sq.ft.       1
₹ 21,495/sq.ft.      1
₹ 30,968/sq.ft.      1
₹ 42,054/sq.ft.      1
₹ 14,166/sq.ft.      1
₹ 1,560/sq.ft.       1
₹ 241,666/sq.ft.     1
₹ 27,191/sq.ft.      1
₹ 160,000/sq.ft.     1
₹ 10,260/sq.ft.      1
₹ 39,074/sq.ft.      1
₹ 38,734/sq.ft.      1
₹ 23,442/sq.ft.      1
₹ 41,833/sq.ft.      1
₹ 600,000/sq.ft.     1
₹ 23,889/sq.ft.      1
₹ 31,915/sq.ft.      1
₹ 14,351/sq.ft.      1
₹ 11,102/sq.ft.      1
₹ 8,866/sq.ft.       1
₹ 36,911/sq.ft.      1
₹ 15,444/sq.ft.      1
₹ 11,240/sq.ft.      1
₹ 15,437/sq.ft.      1
₹ 15,926/sq.ft.      1
₹ 20,115/sq.ft.      1
₹ 40,850/sq.ft.      1
₹ 15,432/sq.ft.      1
₹ 27,390/sq.ft.      1
₹ 30,728/sq.ft.      1
₹ 41,315/sq.ft.      1
₹ 3,786/sq.ft.       1
₹ 9,349/sq.ft.       1
₹ 23,504/sq.ft.      1
₹ 234,375/sq.ft.     1
₹ 21,786/sq.ft.      1
₹ 21,251/sq.ft.      1
₹ 26,111/sq.ft.      1
₹ 27,160/sq.ft.      1
₹ 35,530/sq.ft.      1
₹ 22,046/sq.ft.      1
₹ 27,132/sq.ft.      1
₹ 22,855/sq.ft.      1
₹ 40,741/sq.ft.      1
₹ 29,333/sq.ft.      1
₹ 290,948/sq.ft.     1
₹ 18,250/sq.ft.      1
₹ 16,319/sq.ft.      1
₹ 14,787/sq.ft.      1
₹ 14,667/sq.ft.      1
₹ 24,510/sq.ft.      1
₹ 11,428/sq.ft.      1
₹ 22,184/sq.ft.      1
₹ 30,247/sq.ft.      1
₹ 20,370/sq.ft.      1
₹ 31,666/sq.ft.      1
₹ 283,333/sq.ft.     1
₹ 18,008/sq.ft.      1
₹ 12,285/sq.ft.      1
₹ 19,293/sq.ft.      1
₹ 20,599/sq.ft.      1
₹ 173,992/sq.ft.     1
₹ 21,367/sq.ft.      1
₹ 20,299/sq.ft.      1
₹ 41,818/sq.ft.      1
₹ 19,231/sq.ft.      1
₹ 6,875/sq.ft.       1
₹ 12,393/sq.ft.      1
₹ 22,331/sq.ft.      1
₹ 20,317/sq.ft.      1
₹ 24,005/sq.ft.      1
₹ 33,404/sq.ft.      1
₹ 23,240/sq.ft.      1
₹ 16,071/sq.ft.      1
₹ 51,440/sq.ft.      1
₹ 28,782/sq.ft.      1
₹ 34,491/sq.ft.      1
₹ 34,351/sq.ft.      1
₹ 47,803/sq.ft.      1
₹ 6,230/sq.ft.       1
₹ 33,665/sq.ft.      1
₹ 20,566/sq.ft.      1
₹ 20,349/sq.ft.      1
₹ 24,202/sq.ft.      1
₹ 23,870/sq.ft.      1
₹ 20,026/sq.ft.      1
₹ 28,787/sq.ft.      1
₹ 12,551/sq.ft.      1
₹ 32,870/sq.ft.      1
₹ 24,573/sq.ft.      1
₹ 18,088/sq.ft.      1
₹ 23,932/sq.ft.      1
₹ 16,600/sq.ft.      1
₹ 21,219/sq.ft.      1
₹ 19,125/sq.ft.      1
₹ 18,885/sq.ft.      1
₹ 15,000/sq.ft.      1
₹ 18,814/sq.ft.      1
₹ 14,000/sq.ft.      1
₹ 266,666/sq.ft.     1
₹ 26,502/sq.ft.      1
₹ 18,808/sq.ft.      1
₹ 10,838/sq.ft.      1
₹ 19,847/sq.ft.      1
₹ 12,037/sq.ft.      1
₹ 17,820/sq.ft.      1
₹ 24,390/sq.ft.      1
₹ 26,063/sq.ft.      1
₹ 79,365/sq.ft.      1
₹ 38,986/sq.ft.      1
₹ 55,556/sq.ft.      1
₹ 16,066/sq.ft.      1
₹ 43,210/sq.ft.      1
₹ 38,611/sq.ft.      1
₹ 27,911/sq.ft.      1
₹ 29,022/sq.ft.      1
₹ 12,837/sq.ft.      1
₹ 12,198/sq.ft.      1
₹ 35,741/sq.ft.      1
₹ 16,666/sq.ft.      1
₹ 8,702/sq.ft.       1
₹ 7,827/sq.ft.       1
₹ 23,556/sq.ft.      1
₹ 10,035/sq.ft.      1
₹ 28,841/sq.ft.      1
₹ 26,615/sq.ft.      1
₹ 62,222/sq.ft.      1
₹ 6,597/sq.ft.       1
₹ 7,870/sq.ft.       1
₹ 28,233/sq.ft.      1
₹ 31,926/sq.ft.      1
₹ 27,083/sq.ft.      1
₹ 19,820/sq.ft.      1
₹ 31,444/sq.ft.      1
₹ 31,790/sq.ft.      1
₹ 235,376/sq.ft.     1
₹ 29,293/sq.ft.      1
₹ 16,004/sq.ft.      1
₹ 27,333/sq.ft.      1
₹ 17,624/sq.ft.      1
₹ 30,864/sq.ft.      1
₹ 161,849/sq.ft.     1
₹ 16,056/sq.ft.      1
₹ 17,707/sq.ft.      1
₹ 10,926/sq.ft.      1
₹ 19,608/sq.ft.      1
₹ 8,089/sq.ft.       1
₹ 6,849/sq.ft.       1
₹ 19,607/sq.ft.      1
₹ 40,000/sq.ft.      1
₹ 34,846/sq.ft.      1
₹ 15,111/sq.ft.      1
₹ 1,087/sq.ft.       1
₹ 18,605/sq.ft.      1
₹ 20,769/sq.ft.      1
₹ 21,097/sq.ft.      1
₹ 25,556/sq.ft.      1
₹ 7,756/sq.ft.       1
₹ 21,825/sq.ft.      1
₹ 16,577/sq.ft.      1
₹ 17,706/sq.ft.      1
₹ 29,074/sq.ft.      1
₹ 37,778/sq.ft.      1
₹ 31,111/sq.ft.      1
₹ 17,213/sq.ft.      1
₹ 18,620/sq.ft.      1
₹ 17,014/sq.ft.      1
₹ 7,750/sq.ft.       1
₹ 7,172/sq.ft.       1
₹ 29,638/sq.ft.      1
₹ 8,137/sq.ft.       1
₹ 7,582/sq.ft.       1
₹ 34,568/sq.ft.      1
₹ 13,513/sq.ft.      1
₹ 19,645/sq.ft.      1
₹ 28,549/sq.ft.      1
₹ 36,883/sq.ft.      1
₹ 27,871/sq.ft.      1
₹ 35,109/sq.ft.      1
₹ 17,692/sq.ft.      1
₹ 38,022/sq.ft.      1
₹ 25,309/sq.ft.      1
₹ 16,990/sq.ft.      1
₹ 14,222/sq.ft.      1
₹ 16,388/sq.ft.      1
₹ 22,075/sq.ft.      1
₹ 11,666/sq.ft.      1
₹ 47,167/sq.ft.      1
₹ 7,937/sq.ft.       1
₹ 20,197/sq.ft.      1
₹ 34,037/sq.ft.      1
₹ 10,123/sq.ft.      1
₹ 28,858/sq.ft.      1
₹ 5,950/sq.ft.       1
₹ 63,492/sq.ft.      1
₹ 45,710/sq.ft.      1
₹ 10,288/sq.ft.      1
₹ 40,775/sq.ft.      1
₹ 99,173/sq.ft.      1
₹ 6,172/sq.ft.       1
₹ 9,111/sq.ft.       1
₹ 80,357/sq.ft.      1
₹ 4,117/sq.ft.       1
₹ 7,308/sq.ft.       1
₹ 8,701/sq.ft.       1
₹ 2,296/sq.ft.       1
₹ 9,793/sq.ft.       1
₹ 6,250/sq.ft.       1
₹ 8,486/sq.ft.       1
₹ 11,717/sq.ft.      1
₹ 7,589/sq.ft.       1
₹ 12,592/sq.ft.      1
₹ 15,384/sq.ft.      1
₹ 7,843/sq.ft.       1
₹ 7,778/sq.ft.       1
₹ 4,666/sq.ft.       1
₹ 7,666/sq.ft.       1
₹ 10,233/sq.ft.      1
₹ 25,960/sq.ft.      1
₹ 28,424/sq.ft.      1
₹ 4,490/sq.ft.       1
₹ 14,729/sq.ft.      1
₹ 25,111/sq.ft.      1
₹ 7,309/sq.ft.       1
₹ 74,074/sq.ft.      1
₹ 8,878/sq.ft.       1
₹ 138,888/sq.ft.     1
₹ 14,286/sq.ft.      1
₹ 8,928/sq.ft.       1
₹ 8,007/sq.ft.       1
₹ 5,698/sq.ft.       1
₹ 28,283/sq.ft.      1
₹ 24,214/sq.ft.      1
₹ 26,613/sq.ft.      1
₹ 29,336/sq.ft.      1
₹ 11,284/sq.ft.      1
₹ 46,906/sq.ft.      1
₹ 11,029/sq.ft.      1
₹ 57,692/sq.ft.      1
₹ 10,482/sq.ft.      1
₹ 25,386/sq.ft.      1
₹ 8,735/sq.ft.       1
₹ 18,667/sq.ft.      1
₹ 2,525/sq.ft.       1
₹ 17,695/sq.ft.      1
₹ 21,519/sq.ft.      1
₹ 17,817/sq.ft.      1
₹ 2/sq.ft.           1
₹ 6,173/sq.ft.       1
₹ 13,888/sq.ft.      1
₹ 20,323/sq.ft.      1
₹ 20,359/sq.ft.      1
₹ 5,833/sq.ft.       1
₹ 11,693/sq.ft.      1
₹ 53,125/sq.ft.      1
₹ 5,472/sq.ft.       1
₹ 20,425/sq.ft.      1
₹ 21,667/sq.ft.      1
₹ 230,547/sq.ft.     1
₹ 10,277/sq.ft.      1
₹ 8,518/sq.ft.       1
₹ 10,555/sq.ft.      1
₹ 557/sq.ft.         1
₹ 8,947/sq.ft.       1
₹ 39,265/sq.ft.      1
₹ 6,083/sq.ft.       1
₹ 8,411/sq.ft.       1
₹ 9,333/sq.ft.       1
₹ 32,291/sq.ft.      1
₹ 41,666/sq.ft.      1
₹ 7,280/sq.ft.       1
₹ 90,000/sq.ft.      1
₹ 10,089/sq.ft.      1
₹ 8,697/sq.ft.       1
₹ 8,500/sq.ft.       1
₹ 23,699/sq.ft.      1
₹ 2,778/sq.ft.       1
₹ 39,886/sq.ft.      1
₹ 15,700/sq.ft.      1
₹ 13,542/sq.ft.      1
₹ 19,097/sq.ft.      1
₹ 7,290/sq.ft.       1
₹ 27,741/sq.ft.      1
₹ 43,534/sq.ft.      1
₹ 45,889/sq.ft.      1
₹ 20,690/sq.ft.      1
₹ 29,716/sq.ft.      1
₹ 16,378/sq.ft.      1
₹ 37,777/sq.ft.      1
₹ 12,519/sq.ft.      1
₹ 27,971/sq.ft.      1
₹ 21,000/sq.ft.      1
₹ 13,622/sq.ft.      1
₹ 13,909/sq.ft.      1
₹ 35,400/sq.ft.      1
₹ 13,623/sq.ft.      1
₹ 122,222/sq.ft.     1
₹ 28,490/sq.ft.      1
₹ 24,170/sq.ft.      1
₹ 34,083/sq.ft.      1
₹ 38,251/sq.ft.      1
₹ 43,066/sq.ft.      1
₹ 53,763/sq.ft.      1
₹ 39,062/sq.ft.      1
₹ 48,889/sq.ft.      1
₹ 38,150/sq.ft.      1
₹ 10,077/sq.ft.      1
₹ 33,200/sq.ft.      1
₹ 32,593/sq.ft.      1
₹ 14,914/sq.ft.      1
₹ 29,861/sq.ft.      1
₹ 41,762/sq.ft.      1
₹ 15,451/sq.ft.      1
₹ 12,938/sq.ft.      1
₹ 9,374/sq.ft.       1
₹ 13,410/sq.ft.      1
₹ 12,027/sq.ft.      1
₹ 19,708/sq.ft.      1
₹ 29,974/sq.ft.      1
₹ 16,039/sq.ft.      1
₹ 14,650/sq.ft.      1
₹ 13,778/sq.ft.      1
₹ 21,250/sq.ft.      1
₹ 38,667/sq.ft.      1
₹ 12,593/sq.ft.      1
₹ 25,514/sq.ft.      1
₹ 17,650/sq.ft.      1
₹ 24,280/sq.ft.      1
₹ 26,423/sq.ft.      1
₹ 8,916/sq.ft.       1
₹ 36,667/sq.ft.      1
₹ 9,028/sq.ft.       1
₹ 4,074/sq.ft.       1
₹ 630/sq.ft.         1
₹ 86,567/sq.ft.      1
₹ 92,857/sq.ft.      1
₹ 88,157/sq.ft.      1
₹ 24,069/sq.ft.      1
₹ 42,032/sq.ft.      1
₹ 13,519/sq.ft.      1
₹ 19,000/sq.ft.      1
₹ 13,331/sq.ft.      1
₹ 40,135/sq.ft.      1
₹ 16,244/sq.ft.      1
₹ 16,999/sq.ft.      1
₹ 10,714/sq.ft.      1
₹ 10,463/sq.ft.      1
₹ 18,750/sq.ft.      1
₹ 27,793/sq.ft.      1
₹ 16,428/sq.ft.      1
₹ 22,006/sq.ft.      1
₹ 28,760/sq.ft.      1
₹ 41,615/sq.ft.      1
₹ 38,703/sq.ft.      1
₹ 12,828/sq.ft.      1
₹ 12,842/sq.ft.      1
₹ 8,557/sq.ft.       1
₹ 17,900/sq.ft.      1
₹ 126,865/sq.ft.     1
₹ 7,727/sq.ft.       1
₹ 3,704/sq.ft.       1
₹ 8,230/sq.ft.       1
₹ 13,095/sq.ft.      1
₹ 29,311/sq.ft.      1
₹ 30,384/sq.ft.      1
₹ 19,818/sq.ft.      1
₹ 1,992/sq.ft.       1
₹ 7,619/sq.ft.       1
₹ 98,214/sq.ft.      1
₹ 13,499/sq.ft.      1
₹ 7,820/sq.ft.       1
₹ 4,000/sq.ft.       1
₹ 14,720/sq.ft.      1
₹ 5,664/sq.ft.       1
₹ 19,753/sq.ft.      1
₹ 76,000/sq.ft.      1
₹ 105,751/sq.ft.     1
₹ 2,500/sq.ft.       1
₹ 8,730/sq.ft.       1
₹ 11,538/sq.ft.      1
₹ 14,583/sq.ft.      1
₹ 6,481/sq.ft.       1
₹ 54,794/sq.ft.      1
₹ 14,245/sq.ft.      1
₹ 6,367/sq.ft.       1
₹ 37,313/sq.ft.      1
₹ 90,909/sq.ft.      1
₹ 10,122/sq.ft.      1
₹ 8,642/sq.ft.       1
₹ 6,707/sq.ft.       1
₹ 8,125/sq.ft.       1
₹ 245,398/sq.ft.     1
₹ 11,904/sq.ft.      1
₹ 9,135/sq.ft.       1
₹ 7,111/sq.ft.       1
₹ 8,012/sq.ft.       1
₹ 183,333/sq.ft.     1
₹ 10,142/sq.ft.      1
₹ 6,667/sq.ft.       1
₹ 12,777/sq.ft.      1
₹ 232/sq.ft.         1
₹ 6,648/sq.ft.       1
₹ 7,075/sq.ft.       1
₹ 8,078/sq.ft.       1
₹ 4,251/sq.ft.       1
₹ 17,584/sq.ft.      1
₹ 5,397/sq.ft.       1
₹ 9,074/sq.ft.       1
₹ 5,583/sq.ft.       1
₹ 3,519/sq.ft.       1
₹ 11,194/sq.ft.      1
₹ 6,981/sq.ft.       1
₹ 6,702/sq.ft.       1
₹ 18,333/sq.ft.      1
₹ 4,877/sq.ft.       1
₹ 7,479/sq.ft.       1
₹ 7,400/sq.ft.       1
₹ 16,003/sq.ft.      1
₹ 9,103/sq.ft.       1
₹ 16,667/sq.ft.      1
₹ 21,875/sq.ft.      1
₹ 4,583/sq.ft.       1
₹ 17,500/sq.ft.      1
₹ 11,407/sq.ft.      1
₹ 20,233/sq.ft.      1
₹ 20,062/sq.ft.      1
₹ 11,494/sq.ft.      1
₹ 25,543/sq.ft.      1
₹ 12,343/sq.ft.      1
₹ 16,892/sq.ft.      1
₹ 3,904/sq.ft.       1
₹ 5,333/sq.ft.       1
₹ 14,323/sq.ft.      1
₹ 4,222/sq.ft.       1
₹ 181,818/sq.ft.     1
₹ 26,620/sq.ft.      1
₹ 9,500/sq.ft.       1
₹ 17,937/sq.ft.      1
₹ 3,254/sq.ft.       1
₹ 218,750/sq.ft.     1
₹ 12,400/sq.ft.      1
₹ 40,909/sq.ft.      1
₹ 6,111/sq.ft.       1
₹ 10,784/sq.ft.      1
₹ 12,162/sq.ft.      1
₹ 8,910/sq.ft.       1
₹ 19,869/sq.ft.      1
₹ 8,796/sq.ft.       1
₹ 7,522/sq.ft.       1
₹ 5,658/sq.ft.       1
₹ 24,545/sq.ft.      1
₹ 7,701/sq.ft.       1
₹ 14,072/sq.ft.      1
₹ 26,000/sq.ft.      1
₹ 24,305/sq.ft.      1
₹ 19,286/sq.ft.      1
₹ 22,634/sq.ft.      1
₹ 26,570/sq.ft.      1
₹ 6,410/sq.ft.       1
₹ 133,079/sq.ft.     1
₹ 21,111/sq.ft.      1
₹ 9,725/sq.ft.       1
₹ 28,674/sq.ft.      1
₹ 4,808/sq.ft.       1
₹ 27,155/sq.ft.      1
₹ 14,492/sq.ft.      1
₹ 14,167/sq.ft.      1
₹ 13,157/sq.ft.      1
₹ 5,888/sq.ft.       1
₹ 7,875/sq.ft.       1
₹ 9,654/sq.ft.       1
₹ 8,222/sq.ft.       1
₹ 13,636/sq.ft.      1
₹ 11,273/sq.ft.      1
₹ 7,627/sq.ft.       1
₹ 5,666/sq.ft.       1
₹ 6,567/sq.ft.       1
₹ 22,068/sq.ft.      1
₹ 66,666/sq.ft.      1
₹ 8,386/sq.ft.       1
₹ 5,778/sq.ft.       1
₹ 78,125/sq.ft.      1
₹ 229,885/sq.ft.     1
₹ 17,955/sq.ft.      1
₹ 25,103/sq.ft.      1
₹ 14,954/sq.ft.      1
₹ 8,784/sq.ft.       1
₹ 6,500/sq.ft.       1
₹ 35,494/sq.ft.      1
₹ 11,464/sq.ft.      1
₹ 11,718/sq.ft.      1
₹ 11,555/sq.ft.      1
₹ 3,874/sq.ft.       1
₹ 7,576/sq.ft.       1
₹ 11,556/sq.ft.      1
₹ 10,378/sq.ft.      1
₹ 11,888/sq.ft.      1
₹ 32,258/sq.ft.      1
₹ 16,389/sq.ft.      1
₹ 31,506/sq.ft.      1
₹ 12,820/sq.ft.      1
₹ 151/sq.ft.         1
₹ 21,195/sq.ft.      1
₹ 105,263/sq.ft.     1
₹ 6,790/sq.ft.       1
₹ 7,916/sq.ft.       1
₹ 211,111/sq.ft.     1
₹ 80,000/sq.ft.      1
₹ 120,000/sq.ft.     1
₹ 22,297/sq.ft.      1
₹ 125,000/sq.ft.     1
₹ 73,333/sq.ft.      1
₹ 315,789/sq.ft.     1
₹ 23,557/sq.ft.      1
₹ 10,224/sq.ft.      1
₹ 3,285/sq.ft.       1
₹ 74,000/sq.ft.      1
₹ 27,139/sq.ft.      1
₹ 23,662/sq.ft.      1
₹ 17,574/sq.ft.      1
₹ 9,091/sq.ft.       1
₹ 33,129/sq.ft.      1
Name: count, dtype: int64

In [39]:
df['price_sq.feet'] = df['price_sq.feet'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [40]:
df.head(2)

,property_name,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN

### bedRoom
- Skipping area and areaWithType for now since it wont match with flat.csv

In [41]:
df['bedRoom'].isnull().sum()

np.int64(52)

In [42]:
df[df['bedRoom'].isnull()]

,property_name,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
60,4 Bedroom House for sale in Sector 86 Gurgaon,dlf new town heights,NaN,7718.0,(297 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,8 Bedroom House for sale in B1 Block Sector 57...,independent,NaN,25535.0,(135 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,6 Bedroom House for sale in DLF Phase 1,independent,NaN,1859.0,(420 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,6 Bedroom House for sale in Sushant Lok Phase 3,ansal sushant residency,NaN,17037.0,(251 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,6 Bedroom House for sale in Sushant Lok Phase 3,ansals florence villa,NaN,10579.0,(321 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,4 Bedroom House for sale in DLF Phase 4,independent,NaN,42194.0,(264 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,8 Bedroom House for sale in Uppals Southend,independent,NaN,15625.0,(268 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,6 Bedroom House for sale in Uppals Southend,uppal southend,NaN,15278.0,(268 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,201388.0,(33 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,4 Bedroom House for sale in Malibu Town,independent,NaN,17187.0,(54 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,5 Bedroom House for sale in Sector 33 Gurgaon,unitech uniworld resorts,NaN,NaN,(420 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,5 Bedroom House for sale in DLF Phase 1,independent,NaN,44444.0,(418 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,3 Bedroom House for sale in South City 1,dlf south city 1,NaN,18928.0,(201 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13622.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
76,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13909.0,(384-392 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
79,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
80,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
81,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13623.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
82,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13910.0,(294-418 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
83,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13910.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
84,4 Bedroom House for sale in Sector 112 Gurgaon,experion windchants,NaN,12027.0,(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
85,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,15700.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
86,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,19708.0,(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
87,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16039.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
88,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,13331.0,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
89,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(468-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
90,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(292-358 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
91,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
96,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(325 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
98,4 Bedroom House for sale in Sector 23 Gurgaon,all punjabi welfare association,NaN,16999.0,(139-279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 23 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['HUDA Sector 23 Market', 'Palam triangle', 'R...",All punjabi welfare association in sector-23 g...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
99,4 Bedroom House for sale in Sector 72 Gurgaon,tata primanti,NaN,10714.0,(650-790 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 72 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Omaxe City Cen...","Tata primanti in sector-72, gurgaon by tata ho...",NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4.5 out ..."
101,5 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,NaN,NaN,(251-704 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
102,3 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,NaN,NaN,(211 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
105,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,18750.0,(372-441 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
106,3 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,19000.0,(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
107,5 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,27793.0,(571-711 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
108,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,22006.0,(372-441 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
110,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,13333.0,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
111,5 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,22222.0,(293-381 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
112,4 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,28760.0,(207 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
113,3 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,16975.0,(301 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
117,4 Bedroom House for sale in Sector 65 Gurgaon,emaar emerald hills,NaN,NaN,(183 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 65 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Emerald Plaza Shopping Mall', 'Southern Peri...","Emaar emerald hills in sector-65 gurgaon, gurg...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
118,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,NaN,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN
123,5 Bedroom House for sale in Sector 111 Gurgaon,puri diplomatic greens,NaN,12828.0,(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN
124,5 Bedroom House for sale in Sector 111 Gurgaon,puri diplomatic greens,NaN,12842.0,(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN
128,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,NaN,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
316,3 Bedroom House for sale in Arjun Nagar,independent,NaN,13333.0,(33 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,2 Bedroom House for sale in Palam Vihar Extension,independent,NaN,6666.0,(49 sq.m.) Carpet Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,2 Bedroom House for sale in Rajiv Nagar,independent,NaN,66666.0,(7 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,7 Bedroom House for sale in Surya Vihar,independent,NaN,7500.0,(372 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,4 Bedroom House for sale in Laxman Vihar Phase 2,laxman vihar phase 2,NaN,13636.0,(41 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
843,6 Bedroom House for sale in Sector 22 Gurgaon,saksham welfare association,NaN,19645.0,(220 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- Since they are mostly empty, its better to remove all these

In [43]:
df = df[~df['bedRoom'].isnull()]

In [44]:
df.shape

(962, 19)

In [45]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [46]:
df.head(3)

,property_name,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### Bathroom

In [47]:
df['bathroom'].isnull().sum()

np.int64(0)

In [48]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype(int)

In [49]:
df.sample(3)

,property_name,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
30,4 Bedroom House for sale in Sector 67 Gurgaon,ansal api esencia,5.46,24170.0,(210 sq.m.) Plot Area,Plot area 251(209.87 sq.m.),4,5,3+ Balconies,"Pooja Room,Study Room,Store Room","C Block Ansal Esencia, Golf Course Ext Road, S...",2 Floors,East,1 to 5 Year Old,"['Proposed Metro corridor', 'N.H-8', 'Golf Cou...",Ansal esencia is a residential group housing p...,"['5 Wardrobe', '8 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4.5 out of..."
885,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,8.25,38194.0,(293 sq.m.) Plot Area,Plot area 350(292.64 sq.m.)Built Up area: 300 ...,4,4,3+ Balconies,"Servant Room,Store Room","Villa No40, Sector 48 Gurgaon, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",4bhk lexuary villa for sell tatvam villa in se...,"['1 Water Purifier', '11 Geyser', '1 Stove', '...","['Centrally Air Conditioned', 'Water purifier'...","['Environment4 out of 5', 'Safety4 out of 5', ..."
245,3 Bedroom House for sale in Surya Vihar,independent,0.45,8411.0,(50 sq.m.) Carpet Area,Carpet area: 535 (49.7 sq.m.),3,2,1 Balcony,NaN,"Surya Vihar, Surya Vihar, Gurgaon, Haryana",1 Floors,NaN,undefined,NaN,Best in class property available at surya viha...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

### balcony

In [50]:
df['balcony'].value_counts()

balcony
3+ Balconies    365
2 Balconies     219
3 Balconies     159
No Balcony      115
1 Balcony       104
Name: count, dtype: int64

In [51]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

### Additional room

In [52]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     81
Pooja Room,Study Room,Servant Room,Store Room    60
Others                                           58
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               33
Pooja Room,Study Room,Servant Room,Others        32
Store Room                                       31
Pooja Room,Servant Room                          24
Study Room                                       19
Study Room,Servant Room                          19
Servant Room,Store Room                          15
Pooja Room,Study Room                            11
Pooja Room,Store Room                            11
Pooja Room,Others                                11
Servant Room,Pooja Room                           8
Servant Room,Others                               8
Pooja Room,Store Room,Study Room,Servant Room     8
Pooja Room,Servant Room,Store Room                7
Store Room,Servant Room                           6
Study Room,Servant Room,Pooja Room,Store Room     6
Servant Room,Pooja Room,Store Room                6
Pooja Room,Servant Room,Others                    5
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room,Store Room     5
Study Room,Pooja Room,Servant Room                5
Servant Room,Store Room,Pooja Room                4
Study Room,Servant Room,Store Room                4
Pooja Room,Servant Room,Study Room,Store Room     4
Study Room,Servant Room,Store Room,Pooja Room     4
Pooja Room,Study Room,Others                      4
Store Room,Pooja Room                             4
Pooja Room,Study Room,Store Room                  3
Study Room,Servant Room,Pooja Room                3
Study Room,Others                                 3
Study Room,Pooja Room,Servant Room,Store Room     3
Study Room,Pooja Room,Store Room,Servant Room     2
Pooja Room,Study Room,Store Room,Servant Room     2
Study Room,Servant Room,Others                    2
Store Room,Pooja Room,Study Room,Servant Room     2
Study Room,Pooja Room                             2
Store Room,Pooja Room,Study Room                  2
Store Room,Pooja Room,Servant Room                2
Servant Room,Study Room,Pooja Room                2
Study Room,Pooja Room,Store Room                  2
Study Room,Store Room                             1
Study Room,Store Room,Pooja Room                  1
Store Room,Pooja Room,Servant Room,Study Room     1
Servant Room,Store Room,Study Room,Pooja Room     1
Servant Room,Study Room,Store Room,Pooja Room     1
Store Room,Servant Room,Study Room,Pooja Room     1
Pooja Room,Store Room,Servant Room                1
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: count, dtype: int64

In [54]:
df['additionalRoom'].isnull().sum()

np.int64(384)

In [56]:
df['additionalRoom'] = df['additionalRoom'].fillna('not available')

In [57]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [58]:
df.head(3)

,property_name,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### floors

In [59]:
df['noOfFloor'].value_counts()

noOfFloor
3 Floors     304
2 Floors     287
1 Floors     180
4 Floors     136
5 Floors       9
0 Floors       6
14 Floors      3
6 Floors       3
11 Floors      2
12 Floors      2
10 Floors      2
16 Floors      1
51 Floors      1
41 Floors      1
27 Floors      1
20 Floors      1
13 Floors      1
21 Floors      1
02 Floors      1
33 Floors      1
Name: count, dtype: int64

In [61]:
df['noOfFloor'].isnull().sum()

np.int64(19)

In [62]:
df['noOfFloor'] = df['noOfFloor'].str.split(' ').str.get(0)

In [63]:
df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [65]:
df.head(3)

,property_name,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [66]:
df[df['floorNum'].isnull()]

,property_name,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
23,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,8.50,26235.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4,4,2,"pooja room,servant room,store room","Sector 48 Gurgaon, Gurgaon, Haryana",NaN,East,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Three side open villa in tatvam villa sector-4...,"['1 Chimney', '1 Modular Kitchen', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
51,8 Bedroom House for sale in Palam Vihar,independent,5.60,17284.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),8,6,3+,"pooja room,study room,servant room,store room","Palam Vihar, Gurgaon, Haryana",NaN,South-West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",360 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Dining Table', '1 Light', '1 Modu...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
181,3 Bedroom House for sale in DLF Phase 3,independent,1.45,26852.0,(50 sq.m.) Plot Area,Plot area 60(50.17 sq.m.),3,3,1,not available,"DLF Phase 3, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...",Interested to sell independent house/villa.Pla...,NaN,['Private Garden / Terrace'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."
230,3 Bedroom House for sale in Ashok Vihar,independent,1.50,10288.0,(135 sq.m.) Plot Area,Plot area 162(135.45 sq.m.)Built Up area: 210 ...,3,3,0,not available,"800 Lane 8 Ashok Vihar Part 1, Ashok Vihar, Gu...",NaN,NaN,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Ground floor and partial first floor built up,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
248,2 Bedroom House for sale in Laxman Vihar Phase 2,independent,4.12,8889.0,(431 sq.m.) Plot Area,Plot area 515(430.61 sq.m.),2,1,3+,not available,"Laxman Vihar Phase 2, Gurgaon, Haryana",NaN,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Shre...","Property next to dhanwapur underpass, which is...",[],NaN,NaN
259,3 Bedroom House for sale in New Palam Vihar Ph...,independent,2.50,5472.0,(372 sq.m.) Plot Area,Plot area 4000(371.61 sq.m.),3,2,1,not available,"B-245, New Palam Vihar Phase 2, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",100 mtr from dwarka express way. On 40ft road,NaN,['Park'],NaN
323,4 Bedroom House for sale in Laxman Vihar,independent,0.65,11111.0,(54 sq.m.) Plot Area,Plot area 65(54.35 sq.m.),4,2,2,not available,"Laxman Vihar, Gurgaon, Haryana",NaN,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Well maintained two storeyed independent house...,"['1 Wardrobe', '1 Exhaust Fan', '10 Light', '1...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
346,1 Bedroom House for sale in Sushant Lok Phase 1,ansal sushant lok plots,3.30,26570.0,(115 sq.m.) Plot Area,Plot area 138(115.39 sq.m.),1,1,0,not available,"Sushant Lok Phase 1, Gurgaon, Haryana",NaN,NaN,By 2027,"['Iffco chowk metro station', 'Huda city centr...","Close proximity to gold souk , huda city centr...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
366,2 Bedroom House for sale in Bhawani Enclave,independent,1.10,73333.0,(14 sq.m.) Plot Area,Plot area 150(13.94 sq.m.),2,2,1,others,"Bhawani Enclave, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['State bank ATM', 'Shri Multispeciality Hospi...","2 side open, 1 drawing room, 1 shop, 1 small r...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,NaN
509,2 Bedroom House for sale in Jacobpura,jacob pura,0.35,9722.0,(33 sq.m.) Built-up Area,Built Up area: 360 (33.45 sq.m.),2,1,0,not available,"15/3, Jacobpura, Jacobpura, Gurgaon, Haryana",NaN,NaN,10+ Year Old,NaN,Independece house for sale in jacobpura near k...,[],NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
543,6 Bedroom House for sale in DLF Phase 2,independent,13.00,45710.0,(264 sq.m.) Plot Area,Plot area 316(264.22 sq.m.),6,8,3+,"pooja room,servant room,study room,store room","DLF Phase 2, Gurgaon, Haryana",NaN,NaN,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Esic...",An impeccable opportunity is here for those wh...,"['1 Water Purifier', '1 Fridge', '1 Sofa', '1 ...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
615,3 Bedroom House for sale in New Colony,independent,6.50,15046.0,(401 sq.m.) Plot Area,Plot area 480(401.34 sq.m.),3,2,3+,not available,"New Colony, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",Old construction house in new colony gurgaon.,[],['Private Garden / Terrace'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
658,12 Bedroom House for sale in Sector 46 Gurgaon,independent,6.81,36911.0,(171 sq.m.) Plot Area,Plot area 205(171.41 sq.m.),12,14,3+,"servant room,others","Sector 46 Gurgaon, Gurgaon, Haryana",NaN,East,0 to 1 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",204 sqyds newly floor wise building with basem...,"['14 Wardrobe', '15 Fan', '1 Exhaust Fan', '13...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
781,4 Bedroom House for sale in Sector 86 Gurgaon,dlf new town heights,2.47,7718.0,(297 sq.m.) Plot Area,Plot area 3200(297.29 sq.m.)Built Up area: 280...,4,4,3+,"pooja room,servant room","Sector 86 Gurgaon, Gurgaon, Haryana",NaN,West,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...",This is beautiful 4 bhk villa in dlf new town ...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
804,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,8.50,26235.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4,4,1,not available,"4 Bed And 4 Bathroom, Sector 48 Gurgaon, Gurga...",NaN,NaN,1 to 5 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",360 sq yard 4 bhk residential villa for sale i...,"['4 Bed', '4 Fan', '1 Exhaust Fan', '4 Light',...","['Maintenance Staff', 'Water Storage', 'Separa...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
811,4 Bedroom House for sale in Sushant Lok Phase 1,ansal sushant lok,10.50,27911.0,(350 sq.m.) Plot Area,Plot area 418(349.5 sq.m.),4,4,2,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",NaN,North-East,10+ Year Old,"['Huda city centre metro station', 'New Life C...",Ansal villa for sale 418 sqyd in d block gated...,"['6 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
814,4 Bedroom House for sale in Sector 26 Gurgaon,independent,4.60,12198.0,(350 sq.m.) Plot Area,Plot area 419(350.34 sq.m.),4,4,3+,not available,"F-5/10, Sector 26 Gurgaon, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...",On the lookout for a spacious house in gurgaon...,[],"['Maintenance Staff', 'Park', 'Visitor Parking...",NaN
952,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,9.00,21251.0,(521 sq.m.) Plot Area,Plot area 5605(520.72 sq.m.)Built Up area: 520...,4,4,3+,"pooja room,servant room,store room","Sector 66 Gurgaon, Gurgaon, Haryana",NaN,South-West,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",A lifestyle designed to satiate all your sense...,"['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment3 out of 5', 'Safety4 out of 5', ..."
965,12 Bedroom House for sale in Uppals Southend,uppal southend,6.75,290948.0,(22 sq.m.) Plot Area,Plot area 232(21.55 sq.m.),12,12,3+,"pooja room,study room,servant room,others","Uppals Southend, Gurgaon, Haryana",NaN,West,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address... Uppal southend sector 49 s block si...,"['22 Wardrobe', '24 Fan', '1 Exhaust Fan', '33...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."

- Dont know how to handle null value and cant delete rows as well, skip for now.

### facing

In [68]:
df.fillna({'facing' : 'NA'},inplace=True)

# Now match it with flats.csv

### `area` column

In [70]:
df['area'] = round((df['price']*10000000)/df['price_sq.feet'])

### `property_type` column

In [72]:
df.insert(loc=1,column='property_type',value='house')

In [73]:
df.head()

,property_name,property_type,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [82]:
df.shape

(962, 20)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 962 entries, 0 to 1039
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    962 non-null    object
 1   property_type    962 non-null    object
 2   society          962 non-null    object
 3   price            945 non-null    float64
 4   price_sq.feet    945 non-null    float64
 5   area             945 non-null    float64
 6   areaWithType     962 non-null    object
 7   bedRoom          962 non-null    int64
 8   bathroom         962 non-null    int64
 9   balcony          962 non-null    object
 10  additionalRoom   962 non-null    object
 11  address          957 non-null    object
 12  floorNum         943 non-null    object
 13  facing           962 non-null    object
 14  agePossession    962 non-null    object
 15  nearbyLocations  846 non-null    object
 16  description      962 non-null    object
 17  furnishDetails   727 non-null    object
 18  features         661 non-null    object
 19  rating           841 non-null    object
dtypes: float64(3), int64(2), object(15)
memory usage: 157.8+ KB

In [76]:
df[df['price'].isnull()]

,property_name,property_type,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
47,5 Bedroom House for sale in Sector 66 Gurgaon,house,emaar mgf marbella,NaN,NaN,NaN,Plot area 350(292.64 sq.m.),5,5,3+,"pooja room,study room,servant room","14a, Sector 66 Gurgaon, Gurgaon, Haryana",3,East,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Excellent location, 24 meter wide road facing ...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '15 L...","['Centrally Air Conditioned', 'Water purifier'...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
367,5 Bedroom House for sale in Sector 108 Gurgaon,house,sobha city,NaN,NaN,NaN,Built Up area: 7331 (681.07 sq.m.),5,1,0,not available,"Sector 109, Sector 108 Gurgaon, Gurgaon, Haryana",1,NA,10+ Year Old,"['Dwarka Sector 21', 'Dwarka Expressway', 'Vas...",Best in class property available at sector 109...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4.5 out of..."
432,5 Bedroom House for sale in Laxman Vihar,house,not applicable,NaN,NaN,NaN,Plot area 670(560.21 sq.m.),5,3,2,not available,"Laxman Vihar, Gurgaon, Haryana",3,NA,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Prat...",I have a house/villa available for sale in sar...,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
440,4 Bedroom House for sale in Udyog Vihar Phase 1,house,independent,NaN,NaN,NaN,Plot area 12000(1114.84 sq.m.),4,4,3+,"servant room,store room","320a, Udyog Vihar Phase 1, Gurgaon, Haryana",4,North,5 to 10 Year Old,"['Indusind bank cyber city metro station', 'Mi...",1. Elevators:\nThe building has a state of the...,"['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
458,7 Bedroom House for sale in Naharpur Rupa,house,independent,NaN,NaN,NaN,Plot area 50(41.81 sq.m.),7,2,2,not available,"Naharpur Rupa, Gurgaon, Haryana",2,South,10+ Year Old,"['Rajiv Chowk Mosque', 'Parmar Dental Clinic &...",Great location\n650meter from nh8\nNear by man...,NaN,['Water Storage'],"['Environment3 out of 5', 'Lifestyle3.5 out of..."
580,5 Bedroom House for sale in DLF Phase 3,house,dlf city plot phase 3,NaN,NaN,NaN,Built Up area: 5000 (464.52 sq.m.),5,5,3+,not available,"V Block, DLF Phase 3, Gurgaon, Haryana",4,North-East,undefined,NaN,"5 bath, semi-Furnished, overlooking garden/par...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
727,12 Bedroom House for sale in DLF Phase 2,house,independent,NaN,NaN,NaN,Plot area 250(209.03 sq.m.)Built Up area: 260 ...,12,12,3+,"pooja room,study room,servant room,others","DLF Phase 2, Gurgaon, Haryana",4,North-East,0 to 1 Year Old,"['Vodafone belvedere towers metro station', 'D...",Its a brand new ultra luxury independent build...,"['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
735,5 Bedroom House for sale in Sector 33 Gurgaon,house,unitech uniworld resorts,NaN,NaN,NaN,Plot area 520(434.79 sq.m.),5,8,3+,"servant room,store room","A-898, Sector 33 Gurgaon, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",5 bhk 520 sqyd villas available at unitech uni...,"['5 Wardrobe', '15 Fan', '1 Exhaust Fan', '5 G...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
764,5 Bedroom House for sale in Sector 66 Gurgaon,house,emaar mgf marbella,NaN,NaN,NaN,Plot area 500(418.06 sq.m.),5,7,3+,"pooja room,store room,study room,servant room","Md-45, Sector 66 Gurgaon, Gurgaon, Haryana",2,NA,5 to 10 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Property is located in very posh area, park fa...","['16 Fan', '1 Exhaust Fan', '8 Geyser', '1 Sto...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
791,5 Bedroom House for sale in Sector 33 Gurgaon,house,unitech uniworld resorts,NaN,NaN,NaN,Plot area 502(419.74 sq.m.),5,7,3+,servant room,"A-8, Sector 33 Gurgaon, Gurgaon, Haryana",3,South-East,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",502 sqyd 5bhk villa available for sale at unit...,NaN,"['Private Garden / Terrace', 'High Ceiling Hei...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
799,16 Bedroom House for sale in DLF Phase 4,house,independent,NaN,NaN,NaN,Plot area 270(225.75 sq.m.),16,16,3+,"pooja room,study room,servant room,others","Super Mart 2, DLF Phase 4, Gurgaon, Haryana",4,North-West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...",Independent building floor wise with stilt and...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
816,5 Bedroom House for sale in Nirvana Country,house,unitech espace,NaN,NaN,NaN,Plot area 360(301.01 sq.m.),5,5,3+,study room,"Nirvana Country, Gurgaon, Haryana",2,NA,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",Urgent for sale villa in nirvana country\nOn w...,"['5 Wardrobe', '5 Fan', '11 Light', '6 AC', 'N...","['Maintenance Staff', 'Water Storage', 'Park',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
840,9 Bedroom House for sale in Sector 45 Gurgaon,house,unitech greenwood city,NaN,NaN,NaN,Plot area 240(200.67 sq.m.),9,9,3+,"study room,servant room","Sector 45 Gurgaon, Gurgaon, Haryana",3,South-East,1 to 5 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...","5 years old built up, ground + first + second,...","['1 Water Purifier', '16 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
916,5 Bedroom House for sale in DLF Phase 2,house,independent,NaN,NaN,NaN,Plot area 502(419.74 sq.m.)Built Up area: 450 ...,5,5,3+,"pooja room,study room,servant room,others","Dlf Phase 2, DLF Phase 2, Gurgaon, Haryana",2,West,1 to 5 Year Old,"['Vodafone belvedere towers metro station', 'D...",Dlf phase 2 very prime location. This villa we...,"['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
999,5 Bedroom House for sale in Sector 33 Gurgaon,house,unitech uniworld resorts,NaN,NaN,NaN,Plot area 520(434.79 sq.m.),5,8,3+,"servant room,store room","A-898, Sector 33 Gurgaon, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",5 bhk 520 sqyd villas available at unitech uni...,"['5 Wardrobe', '15 Fan', '1 Exhaust Fan', '5 G...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment3 out of 5', 'Safety4 out of 5', ..."
1019,4 Bedroom House for sale in Sector 66 Gurgaon,house,emaar mgf marbella,NaN,NaN,NaN,Plot area 350(292.64 sq.m.)Built Up area: 6500...,4,4,3+,"pooja room,study room,servant room,store room","Sector 66 Gurgaon, Gurgaon, Haryana",3,North,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",This is 350 sq.Yd villa in the heart of the ci...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment3 out of 5', 'Safety4 out of 5', ..."
1020,5 Bedroom House for sale in Sector 66 Gurgaon,house,emaar mgf marbella,NaN,NaN,NaN,Plot area 350(292.64 sq.m.),5,5,3,not available,"Sector 66 Gurgaon, Gurgaon, Haryana",2,NA,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",This property situated in marbella sector 65 g...,"['5 Fan', '1 Exhaust Fan', '6 Geyser', '1 Micr...","['Private Garden / Terrace', 'Maintenance Staf...","['Environment3 out of 5', 'Safety4 out of 5', ..."

In [80]:
print(df.loc[999, 'description'])

5 bhk 520 sqyd villas available at unitech uniworld resorts, sector 33. Gated society, front rear lawns, roof top jacuzzi, private elevator, private parking

In [83]:
df = df[~df['price'].isnull()]

In [84]:
df.shape

(945, 20)

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 945 entries, 0 to 1039
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    945 non-null    object
 1   property_type    945 non-null    object
 2   society          945 non-null    object
 3   price            945 non-null    float64
 4   price_sq.feet    945 non-null    float64
 5   area             945 non-null    float64
 6   areaWithType     945 non-null    object
 7   bedRoom          945 non-null    int64
 8   bathroom         945 non-null    int64
 9   balcony          945 non-null    object
 10  additionalRoom   945 non-null    object
 11  address          940 non-null    object
 12  floorNum         926 non-null    object
 13  facing           945 non-null    object
 14  agePossession    945 non-null    object
 15  nearbyLocations  830 non-null    object
 16  description      945 non-null    object
 17  furnishDetails   715 non-null    object
 18  features         647 non-null    object
 19  rating           825 non-null    object
dtypes: float64(3), int64(2), object(15)
memory usage: 155.0+ KB

# Save it

In [86]:
df.to_csv('house_cleaned.csv',index=False)

# Merging Flats and Houses

In [87]:
flats = pd.read_csv('flats_cleaned.csv')
houses = pd.read_csv('house_cleaned.csv')

In [88]:
df = pd.concat([flats,houses],ignore_index=True)

In [89]:
# Randomize the data
df = df.sample(df.shape[0],ignore_index=True)

In [90]:
df.head()

,property_name,property_type,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 70A Gurgaon,flat,bptp astaire gardens,1.20,7058.0,1700.0,Super Built up area 1700(157.94 sq.m.)Built Up...,3,3,3+,not available,"Sector 70A Gurgaon, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Sector 54 Chowk Metro Station', 'Airia Mall'...",Having very good quality of wooden work and it...,"['5 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Intercom Facility', 'Lift(s)', 'Swimming Poo...","['Green Area4 out of 5', 'Construction5 out of..."
1,8 Bedroom House for sale in Sector 56 Gurgaon,house,independent,7.50,23148.0,3240.0,Plot area 360(301.01 sq.m.),8,8,3+,"pooja room,study room,servant room","Sector 56 Gurgaon, Gurgaon, Haryana",3.0,North-East,1 to 5 Year Old,"['Sector metro station', 'Sector metro station...",8 bhk luxury kothi for sale in sector -56 clos...,"['1 Water Purifier', '25 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,3 BHK Flat in Sector 83 Gurgaon,flat,vatika lifestyle homes,1.15,8214.0,1400.0,Super Built up area 1832(170.2 sq.m.)Carpet ar...,3,3,1,not available,"Block A, Sector 83 Gurgaon, Gurgaon, Haryana",7.0,South-West,5 to 10 Year Old,"['Sapphire 83 Mall', 'NH – 08', 'Knowledge Tre...",For the actual picture please let us know if t...,"['3 Wardrobe', '2 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4 out ..."
3,6 Bedroom House for sale in Laxmi Garden,house,independent,2.10,17284.0,1215.0,Plot area 135(112.88 sq.m.),6,6,3+,not available,"Near Tiokna Park, Laxmi Garden, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Rachna Dental Clinic',...",Triple story corner big house size 30 feet x 4...,"['3 Chimney', 'No AC', 'No Bed', 'No Curtains'...","['Water Storage', 'Visitor Parking', 'Waste Di...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
4,3 BHK Flat in Sector 102 Gurgaon,flat,emaar gurgaon greens,1.40,8484.0,1650.0,Super Built up area 1650(153.29 sq.m.)Built Up...,3,3,3,servant room,"Sector 102 Gurgaon, Gurgaon, Haryana",10.0,East,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...",Beautiful 3 bhk servant available for sale in ...,"['3 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4 out of..."

In [91]:
df.to_csv('gurgaon_data.csv',index=False)