### This file is handling sector column. Since the project later involves showing analysis based on sectors, this file create new feature called sector which will show sector for each property. 
### It also handles some redundant features.

In [1]:
import pandas as pd
import numpy as np
import re

In [3]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_csv('gurgaon_data.csv')
df.sample(3)

,property_name,property_type,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1090,2 BHK Flat in Sector 95 Gurgaon,flat,sidhartha ncr one,0.56,4106.0,1364.0,Built Up area: 1364 (126.72 sq.m.)Carpet area:...,2,2,2,not available,"Sector 95 Gurgaon, Gurgaon, Haryana",10.0,NaN,undefined,NaN,"2 bath, unfurnished, 10th floor (Of 17), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4.5 out of..."
1294,3 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,1.32,8411.0,1569.0,Super Built up area 1568(145.67 sq.m.),3,3,1,pooja room,"12th Floor, Sector 69 Gurgaon, Gurgaon, Haryana",12.0,South-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Tulip violet is one of gurgaon's most sought a...,"['2 Wardrobe', '6 Fan', '1 Exhaust Fan', '9 Li...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction4 out of..."
497,3 BHK Flat in Sector 37D Gurgaon,flat,ramprastha primera,1.02,6000.0,1700.0,Super Built up area 1700(157.94 sq.m.),3,2,3,not available,"Sector 37D Gurgaon, Gurgaon, Haryana",22.0,NaN,Under Construction,"['JMS Marine Square Mall', 'HUDA Market', 'Dwa...",Residential apartment for sell.The property ha...,[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [5]:
df.shape

(3941, 20)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3941 entries, 0 to 3940
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3941 non-null   object
 1   property_type    3941 non-null   object
 2   society          3940 non-null   object
 3   price            3941 non-null   float64
 4   price_sq.feet    3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3941 non-null   object
 7   bedRoom          3941 non-null   int64
 8   bathroom         3941 non-null   int64
 9   balcony          3941 non-null   object
 10  additionalRoom   3941 non-null   object
 11  address          3930 non-null   object
 12  floorNum         3922 non-null   float64
 13  facing           2770 non-null   object
 14  agePossession    3940 non-null   object
 15  nearbyLocations  3735 non-null   object
 16  description      3941 non-null   object
 17  furnishDetails   2915 non-null   object
 18  features         3236 non-null   object
 19  rating           3493 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 615.9+ KB

### Lets check null values

In [9]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                 0
price_sq.feet         0
area                  0
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             19
facing             1171
agePossession         1
nearbyLocations     206
description           0
furnishDetails     1026
features            705
rating              448
dtype: int64

### Getting sector info from property_name feature

In [10]:
df.head(3)

,property_name,property_type,society,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 70A Gurgaon,flat,bptp astaire gardens,1.20,7058.0,1700.0,Super Built up area 1700(157.94 sq.m.)Built Up...,3,3,3+,not available,"Sector 70A Gurgaon, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Sector 54 Chowk Metro Station', 'Airia Mall'...",Having very good quality of wooden work and it...,"['5 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Intercom Facility', 'Lift(s)', 'Swimming Poo...","['Green Area4 out of 5', 'Construction5 out of..."
1,8 Bedroom House for sale in Sector 56 Gurgaon,house,independent,7.50,23148.0,3240.0,Plot area 360(301.01 sq.m.),8,8,3+,"pooja room,study room,servant room","Sector 56 Gurgaon, Gurgaon, Haryana",3.0,North-East,1 to 5 Year Old,"['Sector metro station', 'Sector metro station...",8 bhk luxury kothi for sale in sector -56 clos...,"['1 Water Purifier', '25 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,3 BHK Flat in Sector 83 Gurgaon,flat,vatika lifestyle homes,1.15,8214.0,1400.0,Super Built up area 1832(170.2 sq.m.)Carpet ar...,3,3,1,not available,"Block A, Sector 83 Gurgaon, Gurgaon, Haryana",7.0,South-West,5 to 10 Year Old,"['Sapphire 83 Mall', 'NH – 08', 'Knowledge Tre...",For the actual picture please let us know if t...,"['3 Wardrobe', '2 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4 out ..."

In [11]:
# Creating new feature
df.insert(loc = 3, column= 'sector', value= df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon', '').str.strip())

In [12]:
df.head()

,property_name,property_type,society,sector,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 70A Gurgaon,flat,bptp astaire gardens,Sector 70A,1.20,7058.0,1700.0,Super Built up area 1700(157.94 sq.m.)Built Up...,3,3,3+,not available,"Sector 70A Gurgaon, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Sector 54 Chowk Metro Station', 'Airia Mall'...",Having very good quality of wooden work and it...,"['5 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Intercom Facility', 'Lift(s)', 'Swimming Poo...","['Green Area4 out of 5', 'Construction5 out of..."
1,8 Bedroom House for sale in Sector 56 Gurgaon,house,independent,Sector 56,7.50,23148.0,3240.0,Plot area 360(301.01 sq.m.),8,8,3+,"pooja room,study room,servant room","Sector 56 Gurgaon, Gurgaon, Haryana",3.0,North-East,1 to 5 Year Old,"['Sector metro station', 'Sector metro station...",8 bhk luxury kothi for sale in sector -56 clos...,"['1 Water Purifier', '25 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,3 BHK Flat in Sector 83 Gurgaon,flat,vatika lifestyle homes,Sector 83,1.15,8214.0,1400.0,Super Built up area 1832(170.2 sq.m.)Carpet ar...,3,3,1,not available,"Block A, Sector 83 Gurgaon, Gurgaon, Haryana",7.0,South-West,5 to 10 Year Old,"['Sapphire 83 Mall', 'NH – 08', 'Knowledge Tre...",For the actual picture please let us know if t...,"['3 Wardrobe', '2 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4 out ..."
3,6 Bedroom House for sale in Laxmi Garden,house,independent,Laxmi Garden,2.10,17284.0,1215.0,Plot area 135(112.88 sq.m.),6,6,3+,not available,"Near Tiokna Park, Laxmi Garden, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Rachna Dental Clinic',...",Triple story corner big house size 30 feet x 4...,"['3 Chimney', 'No AC', 'No Bed', 'No Curtains'...","['Water Storage', 'Visitor Parking', 'Waste Di...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
4,3 BHK Flat in Sector 102 Gurgaon,flat,emaar gurgaon greens,Sector 102,1.40,8484.0,1650.0,Super Built up area 1650(153.29 sq.m.)Built Up...,3,3,3,servant room,"Sector 102 Gurgaon, Gurgaon, Haryana",10.0,East,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...",Beautiful 3 bhk servant available for sale in ...,"['3 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4 out of..."

In [13]:
df['sector'] = df['sector'].str.lower()

In [14]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    58
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 37c                                                    53
sector 70                                                     53
nirvana country                                               52
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 103                                                    45
sector 113                                                    43
dlf phase 1                                                   43
sector 61                                                     42
sector 82                                                     42
sector 66                                                     42
dlf phase 2                                                   41
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 54                                                     27
sector 71                                                     27
laxman vihar                                                  26
dlf phase 4                                                   25
sector 112                                                    24
sector 88a                                                    23
sector 67a                                                    22
sector 111                                                    22
dlf phase 3                                                   21
sector 82a                                                    20
sector 22                                                     20
sector 33                                                     20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 62                                                     17
sector 91                                                     17
sushant lok phase 3                                           16
sector 99                                                     16
sector 110                                                    16
sector 60                                                     15
sector 14                                                     15
sector 63                                                     15
sector 53                                                     14
dlf phase 5                                                   14
sector 76                                                     14
sector 3                                                      14
sector 1 imt manesar                                          14
sector 52                                                     14
rajendra park                                                 14
gwal pahari                                                   14
sector 36a                                                    13
laxman vihar phase 2                                          13
sector 46                                                     13
sector 31                                                     12
uppals southend                                               12
sector 38                                                     12
sector 39                                                     12
sector 50                                                     12
sohna road                                                    12
sector 9a                                                     11
sector 47                                                     11
sector 93                                                     11
ashok vihar phase 3 extension                                 11
sector 1a imt manesar                                         10
sector 7                                                      10
ashok vihar phase 2                                            9
sector 95a                                                     9
sector 4                                                       9
sector 55                                                      9
south city 1                                                   9
dwarka expressway                                              8
sector 40                                                      8
sector 10a                                                     8
sector 43                                                      8
mehrauli  road                                                 8
sector 59                                                      8
sector 57                                                      8
c block sushant lok phase 1                                    8
sector 89 a                                                    8
palam vihar extension                                          8
malibu town                                                    8
sector 26                                                      7
surat nagar 1                                                  7
sector 36 sohna                                                7
mianwali colony                                                7
sector 51                                                      7
sector 58                                                      7
new colony                                                     7
sector 5                                                       6
rajiv nagar                                                    6
sector 11                                                      6
jyoti park                                                     6
jacobpura                                                      6
sector 1                                                       6
ashok vihar                                                    6
new palam vihar                                                5
greenwood city                                                 5
sushant lok phase 2                                            5
arjun nagar                                                    5
sector 9                                                       5
dayanand colony                                                5
saraswati vihar                                                5
sector 2                                                       5
ansal plaza                                                    5
manesar                                                        5
sector 80                                                      5
sector 23a                                                     5
subhash nagar                                                  5
sector 28                                                      5
sector 30                                                      5
chakkarpur                                                     5
sector 105                                                     5
dharam colony                                                  4
devilal colony                                                 4
ravi nagar                                                     4
baldev nagar                                                   4
adarsh nagar                                                   4
sector 36                                                      4
sector 17                                                      4
new                                                            4
valley view estate                                             4
sector 3a                                                      4
garhi harsaru                                                  4
krishna colony                                                 4
shivpuri                                                       4
surya vihar                                                    4
imt manesar                                                    4
sector 12                                                      4
shivaji nagar                                                  4
sector 12a                                                     4
bhondsi                                                        4
vishnu garden                                                  4
madanpuri                                                      4
bhim nagar                                                     4
suncity                                                        4
sector 6                                                       4
prem nagar                                                     3
sector 17b                                                     3
sector 88b                                                     3
sector 17a                                                     3
gandhi nagar                                                   3
sector 8                                                       3
sector 73                                                      3
b block sushant lok phase 1                                    3
sector 45                                                      3
sector 27                                                      3
mg road                                                        3
sector 23                                                      3
sector 110 a                                                   3
patel nagar                                                    3
sector 15                                                      3
a block sushant lok phase 1                                    3
maruti kunj                                                    3
laxmi garden                                                   3
sheetla colony                                                 2
nars                                                           2
rosewood                                                       2
new palam vihar phase 2                                        2
sector 15 part 2                                               2
mohan nagar                                                    2
bhawani enclave                                                2
samaspur                                                       2
surat nagar phase 2                                            2
, delhi ncr                                                    2
acharya puri                                                   2
sector 32                                                      2
new basti                                                      2
sector-2 sohna                                                 2
daulatabad                                                     2
shanti nagar                                                   2
new palam vihar phase 1                                        2
ambience island                                                2
sector 24                                                      2
shankar vihar                                                  2
block a surya vihar                                            2
sector-11 sohna                                                2
sector 15 part 1                                               2
sispal vihar                                                   2
hira nagar                                                     2
lajpat nagar                                                   2
sector 21                                                      2
sohna  road                                                    2
pratap nagar                                                   2
mayfield garden                                                2
golf course ext road                                           2
surat nagar                                                    2
sector 41                                                      2
faridabad road                                                 2
golf course road                                               2
rajiv chowk                                                    2
farukhnagar                                                    2
iffco chowk                                                    2
west rajiv nagar                                               2
manohar nagar                                                  2
shakti nagar                                                   2
sushant lok                                                    2
bissar                                                         2
shivji park colony                                             1
near euro                                                      1
sector 17c                                                     1
urban estate, sector 5                                         1
sultanpur                                                      1
tekchand nagar                                                 1
old delhi road, opp sector-14                                  1
ram nagar                                                      1
devi lal colony gali no 12 gurgaon nr omkar public school      1
part 3 sector 5                                                1
gopal nagar, garhi ghasita, sonipat                            1
saraswati enclave                                              1
v block dlf phase 3                                            1
civil l                                                        1
mahavir pura                                                   1
kanahi                                                         1
near pataudi chowk                                             1
park view                                                      1
bhora kalan                                                    1
om nagar                                                       1
kheri                                                          1
huda saraswati vihar                                           1
near khandsa road                                              1
sadar bazar                                                    1
near sector 1 market                                           1
nirvana country pocket h                                       1
new jyoti park                                                 1
jat colony,fazilpur/taj nagar road                             1
g block dlf city phase 1                                       1
sector 37b                                                     1
saroop garden rajendra park                                    1
begampur khatola                                               1
hsiidc plot sector 1 imt manesar                               1
block h ashok vihar phase iii extension                        1
sector-5 sohna                                                 1
dhankot                                                        1
sector 5 chowk                                                 1
vir nagar                                                      1
rattan garden                                                  1
carterpuri village                                             1
sec 3 bhim vihar part 1 bhimgher kheri                         1
new colony, sector 7                                           1
khandsa                                                        1
mahalaxmi garden, rajendra place                               1
anand garden, sector-105                                       1
near nand hospital                                             1
sector 4 urban estate                                          1
laxmna vihar, phase 2                                          1
block g sector-57                                              1
sector 37a                                                     1
sector-35 sohna                                                1
ashok vihar phase i                                            1
sector 13                                                      1
godrej aria , sector 79 ,                                      1
b1 block sector 57                                             1
garauli kalan                                                  1
damdma                                                         1
laxman vihar, railway road,                                    1
cyber city                                                     1
sai kunj                                                       1
pataudi road                                                   1
sector 21a faridabad                                           1
south city                                                     1
sector-5 sheetla colony                                        1
ansal's palam vihar                                            1
sector 42                                                      1
sector 9b                                                      1
bptp                                                           1
alipur                                                         1
lucknow                                                        1
bhimgarh kheri phase 3                                         1
sector-7 hous                                                  1
heritage city                                                  1
jacobpura near sadar bazar                                     1
rajiv colony                                                   1
ashok vihar phase 3                                            1
ats marigold                                                   1
hno 13 sagar enclave sura                                      1
ravi nager basai road                                          1
Name: count, dtype: int64

#### This is the tricky part. Since many just have sector name instead of no., i need to manually fix this.

In [15]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [16]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [17]:
df['sector'].value_counts()

sector
sohna road                                                   175
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 90                                                     90
sector 81                                                     90
sector 65                                                     90
sector 109                                                    88
sector 79                                                     80
sector 104                                                    73
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 50                                                     64
sector 107                                                    60
sector 108                                                    58
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 2                                                      55
sector 70a                                                    54
sector 70                                                     53
sector 43                                                     53
sector 37c                                                    53
sector-33 sohna road                                          51
sector 84                                                     51
sector 26                                                     50
sector 67                                                     48
sector 49                                                     48
sector 28                                                     46
sector 103                                                    45
sector 113                                                    43
sector 82                                                     42
sector 61                                                     42
sector 66                                                     42
sector 25                                                     41
sector 7                                                      39
sector 106                                                    38
sector 4                                                      35
sector 99a                                                    32
sector 54                                                     31
sector 12                                                     30
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 71                                                     27
sector 5                                                      26
sector 57                                                     24
sector 112                                                    24
sector 14                                                     23
sector 24                                                     23
sector 88a                                                    23
sector 105                                                    23
sector 67a                                                    22
sector 111                                                    22
sector 22                                                     20
sector 3                                                      20
sector 33                                                     20
sector 82a                                                    20
sector 47                                                     19
sector 78                                                     19
sector 11                                                     19
sector 63a                                                    18
gwal pahari                                                   18
sector 74                                                     18
sector 91                                                     17
sector 62                                                     17
sector 99                                                     16
sector 110                                                    16
sector 63                                                     15
sector 60                                                     15
sector 76                                                     14
sector 55                                                     14
sector 53                                                     14
sector 52                                                     14
sector 1 manesar                                              14
sector 6                                                      13
sector 36a                                                    13
sector 4 phase 2                                              13
sector 9                                                      13
sector 46                                                     13
sector 39                                                     12
sector 31                                                     12
sector 38                                                     12
sector 41                                                     11
sector 9a                                                     11
sector 93                                                     11
sector 13                                                     10
sector 1a manesar                                             10
manesar                                                        9
sector 95a                                                     9
sector 8                                                       8
sector 23                                                      8
dwarka expressway                                              8
c block sector 43                                              8
sector 2 extension                                             8
sector 40                                                      8
sector 59                                                      8
sector 10a                                                     8
sector 45                                                      8
sector 17                                                      8
sector 89 a                                                    8
sector 36 sohna road                                           7
sector 51                                                      7
sector 58                                                      7
sector 1                                                       6
sector 21                                                      6
sector 80                                                      5
sector 23a                                                     5
new sector 2                                                   5
sector 30                                                      5
sector 12a                                                     4
sector 36                                                      4
sector 3a                                                      4
new                                                            4
sector 88b                                                     3
sector 73                                                      3
sector 17a                                                     3
sector 110 a                                                   3
a block sector 43                                              3
maruti kunj                                                    3
sector 27                                                      3
sector 17b                                                     3
patel nagar                                                    3
b block sector 43                                              3
sector 15                                                      3
mohan nagar                                                    2
acharya puri                                                   2
sushant lok                                                    2
surat nagar phase 2                                            2
sector-2 sohna road                                            2
bissar                                                         2
ambience island                                                2
daulatabad                                                     2
new basti                                                      2
sector 32                                                      2
samaspur                                                       2
new sector 2 phase 2                                           2
nars                                                           2
rosewood                                                       2
bhawani enclave                                                2
shanti nagar                                                   2
, delhi ncr                                                    2
sector 15 part 2                                               2
sheetla colony                                                 2
mayfield garden                                                2
iffco chowk                                                    2
hira nagar                                                     2
block a sector 21                                              2
golf course ext road                                           2
manohar nagar                                                  2
rajiv chowk                                                    2
faridabad road                                                 2
shankar vihar                                                  2
west sector 13                                                 2
pratap nagar                                                   2
lajpat nagar                                                   2
sector 15 part 1                                               2
sector-11 sohna road                                           2
farukhnagar                                                    2
sispal vihar                                                   2
new sector 2 phase 1                                           2
sohna road  road                                               2
surat nagar                                                    2
golf course road                                               2
g block dlf city phase 1                                       1
old delhi road, opp sector-14                                  1
near euro                                                      1
civil l                                                        1
shivji park colony                                             1
tekchand nagar                                                 1
om nagar                                                       1
part 3 sector 5                                                1
bhora kalan                                                    1
sultanpur                                                      1
near pataudi chowk                                             1
urban estate, sector 5                                         1
block h sector 3 phase iii extension                           1
sector 17c                                                     1
saroop garden sector 105                                       1
gopal nagar, garhi ghasita, sonipat                            1
new sector 7                                                   1
sadar bazar                                                    1
sector 37b                                                     1
park view                                                      1
begampur khatola                                               1
kheri                                                          1
v block sector 24                                              1
kanahi                                                         1
near khandsa road                                              1
ram nagar                                                      1
mahavir pura                                                   1
near sector 1 market                                           1
sector 50 pocket h                                             1
jat colony,fazilpur/taj nagar road                             1
devi lal colony gali no 12 gurgaon nr omkar public school      1
huda sector 28                                                 1
saraswati enclave                                              1
sector-5 sohna road                                            1
near nand hospital                                             1
sai kunj                                                       1
dhankot                                                        1
sector 5 chowk                                                 1
vir nagar                                                      1
rattan garden                                                  1
carterpuri village                                             1
sec 3 bhim vihar part 1 bhimgher kheri                         1
sector 7, sector 7                                             1
khandsa                                                        1
hsiidc plot sector 1 manesar                                   1
mahasector 11, rajendra place                                  1
anand garden, sector-105                                       1
sector 4 urban estate                                          1
laxmna vihar, phase 2                                          1
block g sector-57                                              1
sector 37a                                                     1
sector-35 sohna road                                           1
sector 3 phase i                                               1
godrej aria , sector 79 ,                                      1
b1 block sector 57                                             1
garauli kalan                                                  1
damdma                                                         1
sector 4, railway road,                                        1
alipur                                                         1
pataudi road                                                   1
sector 21a faridabad                                           1
south city                                                     1
sector-5 sheetla colony                                        1
ansal's sector 2                                               1
sector 42                                                      1
sector 9b                                                      1
bptp                                                           1
lucknow                                                        1
cyber city                                                     1
bhimgarh kheri phase 3                                         1
sector-7 hous                                                  1
heritage city                                                  1
sector 12 near sadar bazar                                     1
rajiv colony                                                   1
sector 3 phase 3                                               1
ats marigold                                                   1
hno 13 sagar enclave sura                                      1
ravi nager basai road                                          1
Name: count, dtype: int64

In [18]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [19]:
df['sector'].value_counts()

sector
sohna road                                                   175
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 90                                                     90
sector 81                                                     90
sector 65                                                     90
sector 109                                                    88
sector 79                                                     80
sector 104                                                    73
sector 33                                                     71
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 43                                                     67
sector 95                                                     66
sector 50                                                     64
sector 89                                                     64
sector 2                                                      63
sector 107                                                    60
sector 108                                                    58
sector 56                                                     57
sector 48                                                     56
sector 70a                                                    54
sector 70                                                     53
sector 37c                                                    53
sector 84                                                     51
sector 26                                                     50
sector 4                                                      48
sector 67                                                     48
sector 49                                                     48
sector 28                                                     46
sector 103                                                    45
sector 113                                                    43
sector 66                                                     42
sector 61                                                     42
sector 82                                                     42
sector 25                                                     41
sector 7                                                      39
sector 106                                                    38
sector 12                                                     37
manesar                                                       33
sector 99a                                                    32
sector 54                                                     31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 71                                                     27
sector 5                                                      26
sector 57                                                     24
sector 112                                                    24
sector 3                                                      24
sector 24                                                     23
sector 14                                                     23
sector 88a                                                    23
sector 105                                                    23
sector 111                                                    22
sector 67a                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 110                                                    19
sector 47                                                     19
sector 11                                                     19
sector 78                                                     19
sector 63a                                                    18
gwal pahari                                                   18
sector 74                                                     18
sector 91                                                     17
sector 62                                                     17
sector 99                                                     16
sector 60                                                     15
sector 63                                                     15
sector 52                                                     14
sector 76                                                     14
sector 55                                                     14
sector 53                                                     14
sector 9                                                      13
sector 23                                                     13
sector 6                                                      13
sector 46                                                     13
sector 36a                                                    13
sector 39                                                     12
sector 38                                                     12
sector 31                                                     12
sector 93                                                     11
sector 41                                                     11
sector 9a                                                     11
sector 36                                                     11
sector 13                                                     10
sector 59                                                      8
sector 10a                                                     8
sector 45                                                      8
dwarka expressway                                              8
sector 8                                                       8
sector 40                                                      8
sector 17                                                      8
sector 51                                                      7
sector 58                                                      7
sector 15                                                      6
sector 1                                                       6
sector 21                                                      6
new sector 2                                                   5
sector 30                                                      5
sector 80                                                      5
new                                                            4
sector 17a                                                     3
sector 27                                                      3
sector 88b                                                     3
sector 17b                                                     3
sector 73                                                      3
mohan nagar                                                    2
golf course road                                               2
shanti nagar                                                   2
sector 15 part 2                                               2
rosewood                                                       2
nars                                                           2
ambience island                                                2
bissar                                                         2
sushant lok                                                    2
sheetla colony                                                 2
bhawani enclave                                                2
hira nagar                                                     2
samaspur                                                       2
sector 32                                                      2
surat nagar phase 2                                            2
west sector 13                                                 2
acharya puri                                                   2
daulatabad                                                     2
, delhi ncr                                                    2
golf course ext road                                           2
new basti                                                      2
shankar vihar                                                  2
sector-2 sohna road                                            2
farukhnagar                                                    2
new sector 2 phase 1                                           2
new sector 2 phase 2                                           2
sispal vihar                                                   2
pratap nagar                                                   2
sector 15 part 1                                               2
manohar nagar                                                  2
sector-11 sohna road                                           2
block a sector 21                                              2
sohna road  road                                               2
surat nagar                                                    2
faridabad road                                                 2
rajiv chowk                                                    2
mayfield garden                                                2
iffco chowk                                                    2
lajpat nagar                                                   2
near euro                                                      1
park view                                                      1
gopal nagar, garhi ghasita, sonipat                            1
old delhi road, opp sector-14                                  1
mahavir pura                                                   1
kanahi                                                         1
v block sector 24                                              1
kheri                                                          1
sadar bazar                                                    1
tekchand nagar                                                 1
shivji park colony                                             1
saroop garden sector 105                                       1
jat colony,fazilpur/taj nagar road                             1
near sector 1 market                                           1
near pataudi chowk                                             1
civil l                                                        1
near khandsa road                                              1
sector 17c                                                     1
urban estate, sector 5                                         1
b1 block sector 57                                             1
godrej aria , sector 79 ,                                      1
part 3 sector 5                                                1
ram nagar                                                      1
devi lal colony gali no 12 gurgaon nr omkar public school      1
saraswati enclave                                              1
begampur khatola                                               1
sultanpur                                                      1
sector 37b                                                     1
g block dlf city phase 1                                       1
new sector 7                                                   1
sector 50 pocket h                                             1
huda sector 28                                                 1
om nagar                                                       1
bhora kalan                                                    1
sector 3 phase i                                               1
sector-35 sohna road                                           1
damdma                                                         1
block h sector 3 phase iii extension                           1
khandsa                                                        1
sector 7, sector 7                                             1
sector-7 hous                                                  1
heritage city                                                  1
sec 3 bhim vihar part 1 bhimgher kheri                         1
sector 12 near sadar bazar                                     1
carterpuri village                                             1
rattan garden                                                  1
rajiv colony                                                   1
sector 3 phase 3                                               1
vir nagar                                                      1
sector 5 chowk                                                 1
ats marigold                                                   1
hno 13 sagar enclave sura                                      1
cyber city                                                     1
dhankot                                                        1
garauli kalan                                                  1
sector 4, railway road,                                        1
bhimgarh kheri phase 3                                         1
lucknow                                                        1
sector 37a                                                     1
hsiidc plot manesar                                            1
block g sector-57                                              1
near nand hospital                                             1
sai kunj                                                       1
pataudi road                                                   1
sector 21a faridabad                                           1
laxmna vihar, phase 2                                          1
south city                                                     1
sector-5 sheetla colony                                        1
ansal's sector 2                                               1
sector 42                                                      1
sector 9b                                                      1
sector 4 urban estate                                          1
anand garden, sector-105                                       1
bptp                                                           1
sector-5 sohna road                                            1
mahasector 11, rajendra place                                  1
alipur                                                         1
ravi nager basai road                                          1
Name: count, dtype: int64

In [20]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1232,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
1434,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2164,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
3418,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
3858,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [21]:
df.loc[[1232, 1434, 2164, 3418, 3858], 'sector'] = 'sector 110'

In [22]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
662,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2537,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2931,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
3281,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN

In [23]:
df.loc[662,'sector'] = 'sector 37'
df.loc[3281,'sector'] = 'sector 92'
df.loc[2537,'sector'] = 'sector 90'
df.loc[2931,'sector'] = 'sector 76'

In [24]:
df['sector'].value_counts()

sector
sohna road                                                   175
sector 102                                                   113
sector 85                                                    110
sector 92                                                    105
sector 69                                                     94
sector 90                                                     91
sector 65                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 104                                                    73
sector 33                                                     71
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 43                                                     67
sector 95                                                     66
sector 89                                                     64
sector 50                                                     64
sector 2                                                      63
sector 107                                                    60
sector 108                                                    58
sector 56                                                     57
sector 48                                                     56
sector 70a                                                    54
sector 37c                                                    53
sector 70                                                     53
sector 84                                                     51
sector 26                                                     50
sector 49                                                     48
sector 4                                                      48
sector 67                                                     48
sector 28                                                     46
sector 103                                                    45
sector 113                                                    43
sector 61                                                     42
sector 82                                                     42
sector 66                                                     42
sector 25                                                     41
sector 7                                                      39
sector 106                                                    38
sector 12                                                     37
manesar                                                       33
sector 99a                                                    32
sector 54                                                     31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 71                                                     27
sector 5                                                      26
sector 3                                                      24
sector 57                                                     24
sector 112                                                    24
sector 110                                                    24
sector 14                                                     23
sector 24                                                     23
sector 105                                                    23
sector 88a                                                    23
sector 111                                                    22
sector 67a                                                    22
sector 82a                                                    20
sector 22                                                     20
sector 11                                                     19
sector 47                                                     19
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
gwal pahari                                                   18
sector 62                                                     17
sector 91                                                     17
sector 99                                                     16
sector 76                                                     15
sector 63                                                     15
sector 60                                                     15
sector 53                                                     14
sector 52                                                     14
sector 55                                                     14
sector 46                                                     13
sector 9                                                      13
sector 6                                                      13
sector 23                                                     13
sector 36a                                                    13
sector 39                                                     12
sector 38                                                     12
sector 31                                                     12
sector 9a                                                     11
sector 93                                                     11
sector 36                                                     11
sector 41                                                     11
sector 13                                                     10
sector 40                                                      8
dwarka expressway                                              8
sector 59                                                      8
sector 8                                                       8
sector 45                                                      8
sector 10a                                                     8
sector 17                                                      8
sector 51                                                      7
sector 58                                                      7
sector 21                                                      6
sector 15                                                      6
sector 1                                                       6
sector 30                                                      5
sector 80                                                      5
sector 88b                                                     3
sector 73                                                      3
sector 17a                                                     3
sector 27                                                      3
sector 17b                                                     3
, delhi ncr                                                    2
bhawani enclave                                                2
farukhnagar                                                    2
shankar vihar                                                  2
iffco chowk                                                    2
sector-2 sohna road                                            2
new basti                                                      2
daulatabad                                                     2
sushant lok                                                    2
sector 32                                                      2
bissar                                                         2
ambience island                                                2
nars                                                           2
rosewood                                                       2
sheetla colony                                                 2
sector 15 part 2                                               2
new sector 2 phase 2                                           2
acharya puri                                                   2
mohan nagar                                                    2
surat nagar phase 2                                            2
samaspur                                                       2
golf course road                                               2
new sector 2 phase 1                                           2
surat nagar                                                    2
manohar nagar                                                  2
block a sector 21                                              2
west sector 13                                                 2
mayfield garden                                                2
sispal vihar                                                   2
lajpat nagar                                                   2
hira nagar                                                     2
golf course ext road                                           2
sector-11 sohna road                                           2
shanti nagar                                                   2
sector 15 part 1                                               2
rajiv chowk                                                    2
sohna road  road                                               2
faridabad road                                                 2
pratap nagar                                                   2
near euro                                                      1
ram nagar                                                      1
shivji park colony                                             1
part 3 sector 5                                                1
devi lal colony gali no 12 gurgaon nr omkar public school      1
tekchand nagar                                                 1
old delhi road, opp sector-14                                  1
sultanpur                                                      1
block h sector 3 phase iii extension                           1
jat colony,fazilpur/taj nagar road                             1
v block sector 24                                              1
near sector 1 market                                           1
sadar bazar                                                    1
near pataudi chowk                                             1
huda sector 28                                                 1
sector 50 pocket h                                             1
new sector 7                                                   1
sector 17c                                                     1
civil l                                                        1
g block dlf city phase 1                                       1
saroop garden sector 105                                       1
gopal nagar, garhi ghasita, sonipat                            1
mahavir pura                                                   1
sector 37b                                                     1
begampur khatola                                               1
kanahi                                                         1
park view                                                      1
urban estate, sector 5                                         1
near khandsa road                                              1
saraswati enclave                                              1
kheri                                                          1
om nagar                                                       1
bhora kalan                                                    1
anand garden, sector-105                                       1
near nand hospital                                             1
garauli kalan                                                  1
sector 5 chowk                                                 1
vir nagar                                                      1
rattan garden                                                  1
sector 37                                                      1
carterpuri village                                             1
sec 3 bhim vihar part 1 bhimgher kheri                         1
sector 7, sector 7                                             1
khandsa                                                        1
hsiidc plot manesar                                            1
mahasector 11, rajendra place                                  1
sector-5 sohna road                                            1
sector 4 urban estate                                          1
laxmna vihar, phase 2                                          1
block g sector-57                                              1
sector 37a                                                     1
sector-35 sohna road                                           1
sector 3 phase i                                               1
godrej aria , sector 79 ,                                      1
b1 block sector 57                                             1
dhankot                                                        1
damdma                                                         1
sai kunj                                                       1
sector 4, railway road,                                        1
pataudi road                                                   1
sector 21a faridabad                                           1
south city                                                     1
sector-5 sheetla colony                                        1
ansal's sector 2                                               1
sector 42                                                      1
sector 9b                                                      1
bptp                                                           1
alipur                                                         1
lucknow                                                        1
bhimgarh kheri phase 3                                         1
sector-7 hous                                                  1
heritage city                                                  1
sector 12 near sadar bazar                                     1
rajiv colony                                                   1
sector 3 phase 3                                               1
ats marigold                                                   1
hno 13 sagar enclave sura                                      1
cyber city                                                     1
ravi nager basai road                                          1
Name: count, dtype: int64

In [26]:
df['sector'].isnull().sum()

np.int64(0)

In [28]:
df.head()

,property_name,property_type,society,sector,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 70A Gurgaon,flat,bptp astaire gardens,sector 70a,1.20,7058.0,1700.0,Super Built up area 1700(157.94 sq.m.)Built Up...,3,3,3+,not available,"Sector 70A Gurgaon, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Sector 54 Chowk Metro Station', 'Airia Mall'...",Having very good quality of wooden work and it...,"['5 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Intercom Facility', 'Lift(s)', 'Swimming Poo...","['Green Area4 out of 5', 'Construction5 out of..."
1,8 Bedroom House for sale in Sector 56 Gurgaon,house,independent,sector 56,7.50,23148.0,3240.0,Plot area 360(301.01 sq.m.),8,8,3+,"pooja room,study room,servant room","Sector 56 Gurgaon, Gurgaon, Haryana",3.0,North-East,1 to 5 Year Old,"['Sector metro station', 'Sector metro station...",8 bhk luxury kothi for sale in sector -56 clos...,"['1 Water Purifier', '25 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,3 BHK Flat in Sector 83 Gurgaon,flat,vatika lifestyle homes,sector 83,1.15,8214.0,1400.0,Super Built up area 1832(170.2 sq.m.)Carpet ar...,3,3,1,not available,"Block A, Sector 83 Gurgaon, Gurgaon, Haryana",7.0,South-West,5 to 10 Year Old,"['Sapphire 83 Mall', 'NH – 08', 'Knowledge Tre...",For the actual picture please let us know if t...,"['3 Wardrobe', '2 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4 out ..."
3,6 Bedroom House for sale in Laxmi Garden,house,independent,sector 11,2.10,17284.0,1215.0,Plot area 135(112.88 sq.m.),6,6,3+,not available,"Near Tiokna Park, Laxmi Garden, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Rachna Dental Clinic',...",Triple story corner big house size 30 feet x 4...,"['3 Chimney', 'No AC', 'No Bed', 'No Curtains'...","['Water Storage', 'Visitor Parking', 'Waste Di...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
4,3 BHK Flat in Sector 102 Gurgaon,flat,emaar gurgaon greens,sector 102,1.40,8484.0,1650.0,Super Built up area 1650(153.29 sq.m.)Built Up...,3,3,3,servant room,"Sector 102 Gurgaon, Gurgaon, Haryana",10.0,East,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...",Beautiful 3 bhk servant available for sale in ...,"['3 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4 out of..."

### features to drop -> property_name, address, description, rating

In [29]:
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [30]:
df.sample(5)

,property_type,society,sector,price,price_sq.feet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
2129,flat,godrej,sector 79,1.33,8531.0,1559.0,Super Built up area 1559(144.84 sq.m.),2,2,3,study room,6.0,North-West,1 to 5 Year Old,"['Vatika Town Square-INXT', 'Naurangpur Road',...",NaN,"['Centrally Air Conditioned', 'Security / Fire..."
2258,house,independent,near euro,1.70,18889.0,900.0,Plot area 100(83.61 sq.m.)Built Up area: 61 sq...,5,4,3+,not available,3.0,East,5 to 10 Year Old,"['Shri Multispeciality Hospital', 'Kamla Hospi...","['1 Water Purifier', '7 Fan', '1 Geyser', '20 ...","['Feng Shui / Vaastu Compliant', 'Water Storag..."
212,flat,puri emerald bay,sector 104,2.25,10465.0,2150.0,Super Built up area 2450(227.61 sq.m.)Carpet a...,3,4,3+,servant room,4.0,North,1 to 5 Year Old,"['Sector-21 Metro Dwarka', 'Gurgaon Dreamz Mal...","['6 Fan', '1 Exhaust Fan', '16 Light', '5 AC',...","['Centrally Air Conditioned', 'Water purifier'..."
1214,flat,bptp freedom park life,sector 57,5.50,8982.0,6123.0,Built Up area: 5010 (465.44 sq.m.),5,6,3+,"pooja room,servant room",19.0,East,5 to 10 Year Old,"['Presidium School Gurgoan', 'Manav Rachna Sch...","['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Water purifier', 'Security / Fire Alarm', 'P..."
1841,flat,eldeco accolade,sohna road,0.73,5775.0,1264.0,Super Built up area 1264(117.43 sq.m.)Carpet a...,2,2,3,pooja room,5.0,West,1 to 5 Year Old,"['Global City Centre', 'Sohna Road', 'Damdama ...",NaN,"['Feng Shui / Vaastu Compliant', 'Intercom Fac..."

In [31]:
df.to_csv('gurgaon_data_v2.csv',index=False)